### ISSUE TITLE
AndroidStudio Error:(13, 20) error: cannot find symbol class AutoValue_HomeKey

### ISSUE THREAD

**Issue by IgorKlv** [Zhuinden/simple-stack#109]
I am trying to implement your basic fragment example yet AutoValue_HomeKey is not found by the IDE

**Comment by Zhuinden** [comment]
It's autogenerated when you do `Rebuild Project`, although if done with Kotlin (although I'd prefer `@Parcelize` + data class then) then you'd need to also `apply plugin 'kotlin-kapt'`
