### ISSUE TITLE
Investigate a way to make `Backstack` accessible from `BackstackManager` even when it's uninitialized

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack#117]
The point here is that until you call `backstackManager.setup()` (or `backstackDelegate.onCreate()`), it actually throws an illegal state exception.

This can make it tricky to get `Backstack` into Dagger (although you can do it with a singleton `BackstackHolder`, but people don't really like doing that). But it also leaves initialization (new destination instead of default home) to be configured from `onCreate`, between creation and between setting the state changer.

**Comment by jhowens89** [comment]
I'm currently trying to pull my backstack into dagger where I want to utilize it inside a Coordinator. One of the motivations is to achieve a level of parity with iOS. 

Could you explain what happens in BackstackDelegate::onCreate that becomes a factor for the Activity::onCreate? I've come across the comment here: https://github.com/Zhuinden/simple-stack/issues/73#issuecomment-357891776 but it's not clear to me. My best guess is that there is a connection between what happens to savedInstanceState after it is passed to BackstackDelegate::onCreate and the restoration logic of FragmentManager, but I haven't been able to pinpoint the connection.

**Comment by Zhuinden** [comment]
BackstackDelegate.onCreate is what instantiates the backstack, which afterwards is kept alive across config changes via onRetainCustomNonConfigurationInstance.

Generally what I did is had 

    @Singleton class BackstackHolder @Inject constructor() {
        lateinit var backstack: Backstack
    }

And a module for backstack which provides it from the backstack holder 

    @Module 
    class BackstackModule {
        @Provides fun backstack(holder: BackstackHolder) = holder.backstack
     }

**Comment by dev-JE02** [comment]
Is this also the solution for this scenario?

An activity is garbage collected where the current keys are arranged this way:

A -> B

Now, expecting that upon restore from savedInstanceState the keys restored will be

A -> B

And yes I am seeing B being displayed on screen (I'm using fragments)

But upon calling goBack(), it becomes clear that A has been discarded.

Is there a way to kind of inject A into the backstack upon restore from savedInstanceState?

**Comment by Zhuinden** [comment]
> Is there a way to kind of inject A into the backstack upon restore from savedInstanceState?

It is the default behavior, and it is properly restored after process death in each samples. I would think that A is lost in your case only if you use replaceTop instead of goTo.

**Comment by Zhuinden** [comment]
I think https://github.com/Zhuinden/simple-stack/issues/120 would solve this.

**Comment by matejdro** [comment]
This is still an issue when using Navigator to create a backstack (backstack is not accessible until `Navigator.install() is called). Is there a better workaround rather than creating `BackstackHolder`?

**Comment by Zhuinden** [comment]
@matejdro this issue is effectively obsolete because BackstackManager no longer exists, please open a new issue + provide a minimal example to see what you're trying to do 🤔

Although Navigator.install *is* the way to hook the retained fragment into the Activity and initialize the backstack, so other than `setDeferredInitialization(true)`, I don't think you'll find it beforehand?
