### ISSUE TITLE
Inject a key on bottom of the backstack when activity is restarted from savedInstanceState?

### ISSUE THREAD

**Issue by dev-JE02** [Zhuinden/simple-stack#118]
An activity is garbage collected where the current keys are arranged this way:

A -> B -> C

Now, expecting that upon restore from savedInstanceState the keys restored will be

A -> C

And yes I am seeing C being displayed on screen (I'm using fragments)

But upon calling `goBack()`, it becomes clear that A has been discarded.

Is there a way to kind of inject A into the backstack upon restore from savedInstanceState?

**Comment by Zhuinden** [comment]
If you need to discard B across process death, then you can register a KeyFilter to remove it from the list of keys that are restored.

However, A is not supposed to be lost, it is the default behavior that the full backstack is kept and restored across process death. 

It's restored when you call `backstackDelegate.onCreate(bundle, nonConfig, defaultKeys)`

**Comment by Zhuinden** [comment]
Is there any chance you can share code that displays the behavior of losing A?

I've used simple-stack in projects and this behavior is unit-tested against. It is impossible to lose state unless you use backstackDelegate without registerForLifecycleCallbacks and you don't call onSaveInstanceState.

**Comment by dev-JE02** [comment]
I will create a sample project that shows this case. I also think maybe it has something to do with my FragmentStateChanger as I kind of changed the original logic it has as seen in your fragments sample

**Comment by Zhuinden** [comment]
If the sample project is done I will look at it.

**Comment by Zhuinden** [comment]
Any luck?

**Comment by Zhuinden** [comment]
Technically this cannot happen if you follow the samples. So something tricky is going on, but in your code.

As I haven't received a sample, I'll just close this for now.
