### ISSUE TITLE
onRetainCustomNonConfigurationInstance is deprecated by androidx because "why not"

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack#119]
https://developer.android.com/jetpack/androidx/androidx-rn#2018-nov

This means I need to revise the BackstackDelegate API ***and*** decide how to track in `onCreate` that now I can no longer get a nullable non-config to decide which one to use.

Although I'm guessing the idea is the same as what I do in BackstackHost.

**Comment by Zhuinden** [comment]
I might introduce a BackstackViewModelDelegate which is a mouthful but you only really need the backstack from it anyway.

**Comment by Zhuinden** [comment]
AndroidX needs to stop being alpha for this to happen.

**Comment by Zhuinden** [comment]
....I should just create a migration guide and delete `BackstackDelegate`. 🤔

**Comment by qrezet** [comment]
correct me if I'm wrong but they seem to be not deprecated.

` /**
     * Use this instead of {@link #onRetainNonConfigurationInstance()}.
     * Retrieve later with {@link #getLastCustomNonConfigurationInstance()}.
     */
    public Object onRetainCustomNonConfigurationInstance() {
        return null;
    }

    /**
     * Return the value previously returned from
     * {@link #onRetainCustomNonConfigurationInstance()}.
     */
    @SuppressWarnings("deprecation")
    public Object getLastCustomNonConfigurationInstance() {
        NonConfigurationInstances nc = (NonConfigurationInstances)
                getLastNonConfigurationInstance();
        return nc != null ? nc.custom : null;
    }`

**Comment by Zhuinden** [comment]
It's only deprecated in AndroidX.... 

.... 

I left on a mission to give you the link, but apparently the outrage was big enough that it's not even deprecated anymore? I only found the Reddit thread talking about said depreciation now. 

That's weird. 

Thanks for the notice!

**Comment by qrezet** [comment]
I was actually looking for the this deprecated thing too and that is the reason why I ended up here. I also don't know why its no longer deprecated. But my guess is that this is because `onRetainCustomNonConfigurationInstance()` and `getLastCustomNonConfigurationInstance()` are being used for retaining the AAC `ViewModel` across configuration.

**Comment by Zhuinden** [comment]
No, it's not. They're using `Activity.onRetainNonConfigurationInstance()` which IIRC already hosted the FragmentManager and the LoaderManager in case of FragmentActivity. Now it also bundles out the ViewModelStore.

**Comment by qrezet** [comment]
Oh yeah you're right! :)

**Comment by qwertyfinger** [comment]
It seems that it's back to being deprecated ¯\\\_(ツ)_/¯
See [Javadoc](https://developer.android.com/reference/androidx/activity/ComponentActivity.html#onRetainCustomNonConfigurationInstance()), [Source](https://android.googlesource.com/platform/frameworks/support/+/8514bc0f4d930b5470435aa365719b2a6a3ad2f3/activity/src/main/java/androidx/activity/ComponentActivity.java#169), and it's also back in [the release notes](https://developer.android.com/jetpack/androidx/releases/activity#1.0.0-alpha01) :)

**Comment by Zhuinden** [comment]
@qwertyfinger

**Comment by Zhuinden** [comment]
Opened https://www.reddit.com/r/androiddev/comments/b908fr/can_someone_explain_to_me_why_aac_is_trying_to/ and hope to see more about it

**Comment by qrezet** [comment]
That reddit post 
"Android Framework View class with "please use Flutter instead for your UI layer"

hahahahaha :)) More like "Please forget all about Android, Please use Flutter instead." :))

**Comment by Zhuinden** [comment]
You're going to love this, because to avoid dependence on AndroidX, I'm going to just remove `BackstackDelegate` as it is, and make using `BackstackManager` easier.

**Comment by Zhuinden** [comment]
Or not.

I'll just update the samples with how to integrate `Backstack` with `ViewModel`, too.
