### ISSUE TITLE
FragmentStateChanger: Top fragment stays detached when in both previous and new states

### ISSUE THREAD

**Issue by matejdro** [Zhuinden/simple-stack#144]
I've found a bug in all FragmentStateChanger classes in samples. 

FragmentStateChanger works by detaching all fragments from old state. After that, top fragment from new state is re-attached. However, re-attaching only happens if [fragment is already un-attached](https://github.com/Zhuinden/simple-stack/blob/320cb7b390f14b4ad7439452164fe54397c7e124/simple-stack-example-basic-kotlin/src/main/kotlin/com/zhuinden/simplestackexamplekotlin/FragmentStateChanger.kt#L41). However, sometimes (maybe due to a bug or oversight from dev that uses the library), backstack might get `goTo` call to the Key that is already at the top of the stack. Easiest way to reproduce is to just call the `goTo` twice:

```
backStack.goTo(OtherKey(""))
backStack.goTo(OtherKey(""))
```

In above case, top fragment is in both new and old state:

1. Top fragment is in old state - detach action is queued (but not yet commited)
2. Top fragment is in new state, but it is NOT detached yet, thus `.attach` call is not made
3. State is commited, top fragment gets detached, but not re-attached. Screen becomes blank.

This also happens in show/hide FragmentStatechangers, just replace attach/detach with show/hide in above text.

**Comment by Zhuinden** [comment]
Regularly if `stateChange.isTopNewStateEqualToPrevious()` then I don't enter the FragmentStateChanger at all because there is an early completion in `handleStateChange`.

**Comment by matejdro** [comment]
I've added example reproduction to your sample (linked by github above this comment).

It is correct that using `isTopNewStateEqualToPrevious` prevents the issue, I've missed the need for that check (I'm using `Navigator` and there appears to be no sample for `Navigator`, only for `BackstackDelegate`). If that makes that issue invalid, feel free to close it.

**Comment by Zhuinden** [comment]
Couldn't really decide which API is better tbh, although considering `onRetainCustomNonConfigurationInstance` is deprecated, there's a chance that Navigator should be the way to go after all...

Anyhoo, there is a sample for Navigator + Fragments in the scoping sample:

https://github.com/Zhuinden/simple-stack/blob/2c410f8e5a33397e72814311b52dd2f57943a88c/simple-stack-example-scoping/src/main/kotlin/com/zhuinden/simplestackexamplescoping/MainActivity.kt#L24-L29

**Comment by Zhuinden** [comment]
while this is tricky, the `isTopNewStateEqualToPrevious()` is the way to go.
