### ISSUE TITLE
FragmentStateChanger: Going back and then immediatelly re-opening same fragment instantiates destroyed fragment

### ISSUE THREAD

**Issue by matejdro** [Zhuinden/simple-stack#145]
Another edge case, similar to #144. When exiting the screen, and then immediatelly re-opening the screen, like this:

```
// I'm on screen A
backStack.goBack()
backStack.goTo(A.Key())
```

This happens:

1. Within `goBack()` transition, fragment is removed. However, it appears that even with `commitNow()`, removal is not immediate. `findFragmentByTag` will still return this removed fragment, I guess until fragment manager can do some cleanup on the next frame.
2. Within `goTo` transition, existing fragment will be fetched via `findFragmentByTag`. Since existing fragment is not null, `FragmentStateChanger` will just show it and call it a day. However, this fragment is in the process of removal and will be removed eventually. This results in invalid fragment object being brought to front.

I have managed to fix this by also making sure existing fragment is not in the process of being removed:
```
val fragment: Fragment? = fragmentManager.findFragmentByTag(newKey.fragmentTag)
if (fragment != null && !fragment.isRemoving) {
...
```
I'm not sure if this causes any other side effects though.

**Comment by matejdro** [comment]
Maybe a better idea would be to just re-add existing fragment in the process of being removed instead of instantiating new fragment? That would be more efficient, but could cause issues with state stored in the fragment object though.

**Comment by Zhuinden** [comment]
You could also try to move `completionCallback.stateChangeComplete()` to `fragmentTransaction.doOnCommit()`.

That way, Backstack's internal enqueueing of ops should guarantee that the FragmentTransaction executes before starting the next.

**Comment by Zhuinden** [comment]
Have you tried `doOnCommit`?

**Comment by matejdro** [comment]
I've added example reproduction to your sample (linked by github above this comment). `doOnCommit` does not help.

**Comment by Zhuinden** [comment]
I marked this as critical and was thinking about it but I'm actually not sure what to do with it.

I don't really want to call `executePendingTransactions()` because you can get erratic results... But I also don't want artificial delay... But it also seems like there just isn't a callback to listen for in this case... :|

The StateChanger can introduce any delay it wants though considering it's a question of "not yet calling" `completionCallback.stateChangeComplete`.

Maybe that really is the only thing one can do.

**Comment by matejdro** [comment]
From my testing, `executePendingTransactions()` also does not help. Did you check out the solution I mentioned above in OP?

**Comment by Zhuinden** [comment]
I actually totally missed that fix (wow I should learn how to read) but I'll check it out, then.

Although it is somewhat scary that while I know that a fragment can be `isRemoving`, I can't know when it stops being that way.

**Comment by Zhuinden** [comment]
Thanks for the report, I've added a demonstration on what one can do about this here: https://github.com/Zhuinden/simple-stack/issues/159#issuecomment-476361384 .

I'm not very fond of the solution itself, but it's definitely one way to work-around the issue.

Fragments suck.

**Comment by Zhuinden** [comment]
I probably should have added an "official fix" much faster than I actually did...

Anyhoo, a *real* fix compared to the workaround presented above is to detect that if the fragment returned by `findFragmentByTag` was `isRemoving`, then also create a new fragment, and use `replace` to add it.

See https://github.com/Zhuinden/simple-stack/commit/dfc5fef9c2f2236651162b8ec8b36062615a1cf6

**Comment by Zhuinden** [comment]
@matejdro they are fixing this problem on Fragment level! See commit https://android.googlesource.com/platform/frameworks/support/+/0f9cd6231fcc3e180b251ee4f9d12e5d3bcbfa83
