### ISSUE TITLE
Keep fragment alive when passing to a new one

### ISSUE THREAD

**Issue by marcosvbras** [Zhuinden/simple-stack#146]
If I'm in a fragment A and pass to fragment B and then go back to A, the fragment A will be recreated. How can I navigate between fragments without destroying them when I call other fragment?

**Comment by Zhuinden** [comment]
That shouldn't happen with any of the FragmentStateChanger implementations I provide if you use `goTo()`.

So the question  is, are you using it in a BottomNavigationView with `setHistory` or `replaceTop`?

**Comment by marcosvbras** [comment]
> That shouldn't happen with any of the FragmentStateChanger implementations I provide if you use `goTo()`.
> 
> So the question is, are you using it in a BottomNavigationView with `setHistory` or `replaceTop`?
> 
> Ah, make sure the key you are using implements toString().

May I use setHistory only in BottomNavigationView or in all fragment transactions?

**Comment by Zhuinden** [comment]
`setHistory` sets the current navigation history to any list of keys you want.

Technically as you don't have code sample all I can do is guess work, but if we're talking about BottomNavigationView then the trick for preserving the state of a fragment is adding it, but keeping it hidden with `FragmentTransaction.hide()` when it's not actually visible.

I did this in production with a slightly tweaked version of the FragmentStateChanger - one that knew to check if a fragment was a "main fragment" (accessible in BottomNavigationView) and those were always added, just kept hidden.

**Comment by Zhuinden** [comment]
The idea is that if you don't want a Fragment to be removed, then it shouldn't be removed. 😉 

Fragments preserve their states as long as they are added to the FragmentManager, and not removed from it.

So the FragmentStateChanger must be changed in such a way that it keeps certain fragments alive - we for example used to keep all the root fragments of a bottom nav view alive.

I assume that answers the question.
