### ISSUE TITLE
onDestroy not called, leaving in broken state for following fragments 

### ISSUE THREAD

**Issue by arberg** [Zhuinden/simple-stack#159]
simple-stack v1.14.0
Android Studio 3.3.2
android support 28.0.0, with supportFragments 
androidx.legacy:legacy-support-v13:1.0.0 - now also tested on androidx instead of old support, same problem

I have a particular scenario where I can get simple-stack and/or androids fragmentManager into a broken state, and I'm at a loss of how to repair the issue. Sometimes when I pop a fragment (backstack.goBack), its onDestroy does not get called. When that happens (that onDestroy is missed on popping), then when I open a new version of same fragment, I get an invisible fragment, probably because my theme is transparant. The new fragment, does not get created because my FragmentStateChanger (directly from sample code-base), does not create a new fragment because fragmentManager already has a fragment by same tag. Indeed debugger inspection of fragmentManager.getActiveFragments() shows me 2 fragments, my main and the popped fragment. So it finds that fragment. But it never calls onCreateView, or onStart, or onResume on that (broken) fragment. Inspection shows the fragment is mCalled=true (whatever that means), and mDetached=false, and mRemoving=true.

If I back out of my app, and open it again without killing VM, it creates a new fragment, but the backstack is now broken, I get the following execption when calling backstack.getHistory().fromTop(1), after opening the 2nd fragment 

java.lang.IllegalArgumentException: The provided offset value [1] was out of range: [-1; 1)
        at com.zhuinden.simplestack.History.fromTop(History.java:75)

I found a hack that I can use in fragmentStateChanger, so I only reuse af fragment if  fragment != null && !fragment.isRemoving(), thus I now still recreate a new fragments. But it leaks all the old broken fragments, the fragment manager holds on to those. I then 'fix' a the bad state, by calling system.exit on activity.onDestroy, if broken state detected (I might be able to do less, but for now it surfices.

I just noticed that when I exit the activity then alle the broken fragments get their onDestroy() called during the activity's super.onDestroy().

I can only reproduce the problem when navigating to my 'problem' fragment from my MainFragment which contains a Map fragment. Maybe that screws with android somehow. I don't see the problem when starting the 'problem' fragment from a deeper fragment. Also I don't see the problem when debugger is attached, but I suspect thats a timing issue.

Any guess at whether its an Android bug or simple-stack or both? Or if its an Android bug, whether you can circumvent it somehow.

**Comment by Zhuinden** [comment]
I've actually heard of this in https://github.com/Zhuinden/simple-stack/issues/145 but didn't realize this could be so severe... we've used Fragments before with simple-stack and this ***never*** happened.

Alas, considering I see that it *can* happen, there's one way to workaround this issue, I would think; which is to make the necessary FragmentTransaction only when there are no fragments that are `isRemoving`.

No, don't ask me why a Fragment can be *isRemoving* even in a synchronous scenario, I have no idea why they don't just remove them. Sure, sure, animations and whatever, but even then this doesn't make sense.

We used to override `dispatchTouchEvent` and we blocked user interaction while the Fragments were expected to be animating (they had a uniform animation duration).

``` kotlin
override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
    return !isAnimating && super.dispatchTouchEvent(ev)
}
```

------------

According to the other guy, this can happen in the following scenario:

``` kotlin
                backstack.goBack()
                backstack.goTo(addOrEditTaskKey)
```

Therefore what we can do is make the FragmentStateChanger resilient enough that it'd ensure waiting until there are no fragments that are `isRemoving`.

---------------

So without further ado, here is this super hacky solution that waits until all Fragments are no longer `isRemoved` in order to execute the next callback. It seems to work fine.

``` kotlin
class SaferFragmentStateChanger(
    private val fragmentManager: FragmentManager,
    private val containerId: Int
) {
    private val handler: Handler = Handler(Looper.getMainLooper())

    fun handleStateChange(stateChange: StateChange, completionCallback: StateChanger.Callback) {
        tryExecutingFragmentTransaction(stateChange, completionCallback)
    }

    fun stopPendingCallback() {
        val pendingCallback = pendingCallback
        if (pendingCallback != null) {
            handler.removeCallbacks(pendingCallback)
        }
    }

    private var pendingCallback: Runnable? = null

    // we must ensure that we execute the fragment transaction only when no fragments are in transient state
    private fun isAnyFragmentRemoving(stateChange: StateChange): Boolean {
        for (newState in stateChange.getNewState<Key>()) {
            val fragment = fragmentManager.findFragmentByTag(newState.fragmentTag)
            if (fragment != null && fragment.isRemoving) {
                return true
            }
        }
        return false
    }

    private fun tryExecutingFragmentTransaction(stateChange: StateChange, completionCallback: StateChanger.Callback) {
        val anyRemoving = isAnyFragmentRemoving(stateChange)
        if (anyRemoving) {
            pendingCallback = Runnable {
                tryExecutingFragmentTransaction(stateChange, completionCallback)
            }
            handler.postDelayed(pendingCallback, 125L)
        } else {
            executeFragmentTransaction(stateChange, completionCallback)
        }
    }

    private fun executeFragmentTransaction(stateChange: StateChange, completionCallback: StateChanger.Callback) {
        pendingCallback = null

        val fragmentTransaction = fragmentManager.beginTransaction().disallowAddToBackStack()
        when (stateChange.direction) {
            StateChange.FORWARD -> {
                fragmentTransaction.setCustomAnimations(R.anim.slide_in_from_right, R.anim.slide_out_to_left)
            }
            StateChange.BACKWARD -> {
                fragmentTransaction.setCustomAnimations(R.anim.slide_in_from_left, R.anim.slide_out_to_right)
            }
            else -> {
                /* do nothing */
            }
        }

        val previousState = stateChange.getPreviousState<Key>()
        val newState = stateChange.getNewState<Key>()
        for (oldKey in previousState) {
            val fragment = fragmentManager.findFragmentByTag(oldKey.fragmentTag)
            if (fragment != null) {
                if (!newState.contains(oldKey)) {
                    fragmentTransaction.remove(fragment)
                } else if (!fragment.isHidden) {
                    fragmentTransaction.hide(fragment)
                }
            }
        }
        for (newKey in newState) {
            val fragment: Fragment? = fragmentManager.findFragmentByTag(newKey.fragmentTag)
            if (newKey == stateChange.topNewState<Any>()) {
                if (fragment != null) {
                    if (fragment.isHidden) {
                        fragmentTransaction.show(fragment)
                    }
                } else {
                    fragmentTransaction.add(containerId, newKey.newFragment(), newKey.fragmentTag)
                }
            } else {
                if (fragment != null && !fragment.isHidden) {
                    fragmentTransaction.hide(fragment)
                }
            }
        }
        fragmentTransaction.commitNow() // had to be `now` in the sample, but you can probably use `allowingStateLoss()`
        completionCallback.stateChangeComplete()
    }
}
```

Refer to https://github.com/Zhuinden/simple-stack/commit/17fca3eb6fc0fe6b592e378d472c7c0c4a3ff6a6

**Comment by Zhuinden** [comment]
One thing to note, `simple-stack` on its own is a backstack that can enqueue operations; the fact that this is happening is totally Fragments' fault (and my oversight in the samples, but then again `fragmentManager.getFragments()` no longer returns this fragment while `fragmentManager.findFragmentByTag()` does - ridiculous.)

**Comment by arberg** [comment]
Wow thank you for your detailed and quick response, that is kind of you.

I did notice #145 but I could also learn to read, or in my case slow down. I just read the goBack+goTo, and that's not my issue, but everything else described in the initial post matches my case exactly. And reading it would probably have saved me lots of time tracking that down.

So I suspect the underlaying root problem could be the same, but its not the same trigger, and so the SaferFragmentStateChanger does not work for me, but thanks a lot for it. The SaferFragmentStateChanger postpones fragmentTransactions, till the last one completes, as seen by no more fragments to be removed. In my case, the old one never completes, because (?) the fragmentManager is broken. The top (2nd) fragment is pop'ed but it never exits the isRemoving state, that is until I do activity.onDestroy. 

I followed the the idea of postponing my actions, and I suspected it must be related to my MainFragment.onStart doing an animated cameraUpdate on its underlying google Map-fragment. If I postpone this camera-change (and any other map-changes) till after onDestroy completes it works, when my delay of 500ms was to little and still was before onDestroy I 'died' once again.

F*ck fragments. I'm glad to have moved to Single-activity coding, but now I would prefer it Google Fragments where also replaced. Its 8 years old, so if still broken, will probably always stay broken.

So what I came up with is a new fragment 'state', BaseFragment.onNavigationComplete now gets called when SaferFragmentStateChanger has completed transactions, and no fragments in previousState list are isRemoving AND topFragment.isResumed, so it gets called after onResume. 

It still sucks, because if I forget in the future, and do stuff in onResume, it silently breaks the app. Now I check if its unexpectedly slow to finish, and reports an error so I might detect it.

Btw, I tried using commit instead of commitNow, and that gave no change.

I tried the SaferFragmentStateChanger 

PS: Thanks for giving me an excuse to include kotlin in my build :)

```
class BaseFragment {
...

    /**
     * Invoked by StateChanger when this fragment has been resumed, and AFTER
     * all fragments are done being removed (including onDsestroy). This prevents a bug in Android where when we change camera
     * location in Map in
     * onResume/onStart on the MainFragment being resumed then Android cannot complete the fragment popping.
     *
     * Note: Will not be called when activity is resumed.
     */
    public void onNavigationComplete() {
        if (DO_LOG) Log.d(getClass().getSimpleName(), "onNavigationComplete()");
    }
...
```

My version of the safer changer

```
package dk.bnr.androidbooking.application

import android.os.Handler
import android.os.Looper
import android.os.SystemClock
import android.support.v4.app.Fragment
import android.support.v4.app.FragmentManager
import android.support.v4.app.FragmentTransaction
import android.util.Log
import com.zhuinden.simplestack.History
import com.zhuinden.simplestack.StateChange
import com.zhuinden.simplestack.StateChanger
import dk.bnr.androidbooking.AndroidBooking
import dk.bnr.androidbooking.CrashlyticsWrapper
import dk.bnr.androidbooking.R
import dk.bnr.androidbooking.gui.viewmodel.ViewModel

class SaferFragmentStateChanger(
        private val activity: AndroidBooking,
        private val fragmentManager: FragmentManager,
        private val containerId: Int
) {
    private val TAG = "StateChanger"
    private val DO_LOG = true
    private val handler: Handler = Handler(Looper.getMainLooper())
    private var pendingCallback: Runnable? = null
    private val useDetach = true // If using show/hide listen in OnHiddenChanged in fragment

    fun handleStateChange(stateChange: StateChange, completionCallback: StateChanger.Callback) {
        // do or postpone, so a goBack immediately followed by goTo, may work
        tryExecutingFragmentTransaction(stateChange, completionCallback)
    }

    // Call from activity.onDestroy
    fun stopPendingCallback() {
        val pendingCallback = pendingCallback
        if (pendingCallback != null) {
            handler.removeCallbacks(pendingCallback)
        }
        this.pendingCallback = null
    }

    // we must ensure that we execute the fragment transaction only when no fragments are in transient state
    private fun isAnyFragmentRemoving(history: History<BaseKey<ViewModel, BaseFragment<ViewModel>>>): Boolean {
        for (newState in history) {
            val fragment = fragmentManager.findFragmentByTag(newState.fragmentTag)
            if (fragment != null && fragment.isRemoving) {
                if (DO_LOG) Log.d(TAG, "fragment.isRemoving=true: " + fragment.javaClass.simpleName)
                return true
            }
        }
        return false
    }

    private fun tryExecutingFragmentTransaction(stateChange: StateChange, completionCallback: StateChanger.Callback) {
        val anyRemoving = isAnyFragmentRemoving(stateChange.getNewState())
        if (anyRemoving) {
            pendingCallback = Runnable {
                tryExecutingFragmentTransaction(stateChange, completionCallback)
            }
            handler.postDelayed(pendingCallback, 125L)
        } else {
            executeFragmentTransaction(stateChange, completionCallback)
        }
    }

    private fun scheduleOnNavigationComplete(previousState: History<BaseKey<ViewModel, BaseFragment<ViewModel>>>, topFragment: BaseFragment<ViewModel>) {
        scheduleOnNavigationComplete(previousState, topFragment, SystemClock.uptimeMillis(), false)
    }

    private fun scheduleOnNavigationComplete(previousState: History<BaseKey<ViewModel, BaseFragment<ViewModel>>>, topFragment: BaseFragment<ViewModel>, timestamp: Long, reportedError: Boolean) {
        // Also listen for isResumed, so we don't call onNavigationComplete before fragment is completed
        val anyRemoving = isAnyFragmentRemoving(previousState) || !topFragment.isResumed
        if (anyRemoving) {
            val toSlow = SystemClock.uptimeMillis() - timestamp > 30000L
            if (toSlow && !reportedError) {
                CrashlyticsWrapper.reportException(RuntimeException("Fragment not finished after 30s: " + topFragment.javaClass.simpleName))
            }
            pendingCallback = Runnable {
                scheduleOnNavigationComplete(previousState, topFragment, timestamp, toSlow || reportedError)
            }
            handler.postDelayed(pendingCallback, 125L)
        } else {
            if (DO_LOG) Log.d(TAG, topFragment.javaClass.simpleName + " onNavigationComplete")
            topFragment.onNavigationComplete()
        }
    }

    private fun executeFragmentTransaction(stateChange: StateChange, completionCallback: StateChanger.Callback) {
        stopPendingCallback()

        val fragmentTransaction = fragmentManager.beginTransaction().disallowAddToBackStack()
        when (stateChange.direction) {
            StateChange.FORWARD -> {
                fragmentTransaction.setCustomAnimations(R.anim.slide_in_from_right, R.anim.slide_out_to_left)
            }
            StateChange.BACKWARD -> {
                fragmentTransaction.setCustomAnimations(R.anim.slide_in_from_left, R.anim.slide_out_to_right)
            }
            else -> {
                /* do nothing */
            }
        }
        val previousState = stateChange.getPreviousState<BaseKey<ViewModel, BaseFragment<ViewModel>>>()
        val newState = stateChange.getNewState<BaseKey<ViewModel, BaseFragment<ViewModel>>>()
        for (oldKey in previousState) {
            val fragment: Fragment? = fragmentManager.findFragmentByTag(oldKey.fragmentTag)
            if (fragment != null) {
                if (!newState.contains(oldKey)) {
                    fragmentTransaction.remove(fragment)
                } else {
                    detachOrHide(fragment, fragmentTransaction)
                }
            }
        }
        var topFragment: BaseFragment<ViewModel>? = null
        for (newKey in newState) {
            val fragment: BaseFragment<ViewModel>? = fragmentManager.findFragmentByTag(newKey.fragmentTag) as? BaseFragment<ViewModel>
            if (newKey == stateChange.topNewState<Any>()) {
                if (fragment != null) {
                    topFragment = fragment
                    attachOrShow(fragment, fragmentTransaction)
                } else {
                    val newFragment: BaseFragment<ViewModel> = newKey.newFragment()
                    topFragment = newFragment
                    newFragment.bindViewModel(activity.backstackDelegate.getService(newKey, newKey.getViewModelTag()))
                    fragmentTransaction.add(containerId, newFragment, newKey.fragmentTag)
                }
            } else {
                detachOrHide(fragment, fragmentTransaction)
            }
        }
        fragmentTransaction.commitNow() // had to be `now` in the sample, but you can probably use `allowingStateLoss()`
        completionCallback.stateChangeComplete()
        if (topFragment != null) {
            scheduleOnNavigationComplete(previousState, topFragment)
        } else {
            throw IllegalStateException("No top fragment")
        }
    }

    private fun attachOrShow(fragment: Fragment?, fragmentTransaction: FragmentTransaction) {
        if (fragment != null) {
            if (useDetach) {
                if (fragment.isDetached) {
                    if (DO_LOG) Log.d(TAG, fragment.javaClass.simpleName + " Attaching")
                    fragmentTransaction.attach(fragment)
                }
            } else {
                if (fragment.isHidden) {
                    if (DO_LOG) Log.d(TAG, fragment.javaClass.simpleName + " Showing")
                    fragmentTransaction.show(fragment)
                }
            }
        }
    }

    private fun detachOrHide(fragment: Fragment?, fragmentTransaction: FragmentTransaction) {
        if (fragment != null) {
            if (useDetach) {
                if (!fragment.isDetached) {
                    if (DO_LOG) Log.d(TAG, fragment.javaClass.simpleName + " Detaching")
                    fragmentTransaction.detach(fragment)
                }
            } else {
                if (!fragment.isHidden) {
                    if (DO_LOG) Log.d(TAG, fragment.javaClass.simpleName + " Hiding")
                    fragmentTransaction.hide(fragment)
                }
            }
        }
    }
}
```

**Comment by Zhuinden** [comment]
I have another idea that might be better than my original "wait until the fragment is removed" then, because the original premise is that the fragment is returned by `findFragmentByTag` even when it is `isRemoved`; a possible option could be to detect when this happens, in which case also create a new fragment but use `replace` instead of `add` (to override the fragment found under that tag).

**Comment by arberg** [comment]
Interesting, I was thinking about something like that, but couldn't remember my way around Fragments.

I tried it, it doesn't work well. It does replace the fragment, so there's seemingly no issue. But old replaced fragments don't get their onDestroy called before activity.onDestroy() and thus leaks. When starting activity again after onDestroy (in same VM), i get the backstack issue where its history is somehow incorrect: 

```
    java.lang.IllegalArgumentException: The provided offset value [1] was out of range: [-1; 1)
        at com.zhuinden.simplestack.History.fromTop(History.java:75)
        at dk.bnr.androidbooking.application.injection.MessageQueue.pushMessageToParent(MessageQueue.java:34)
        at dk.bnr.androidbooking.gui.viewmodel.DestinationViewModel.onSelectedAddress(DestinationViewModel.java:34)
```

So in effect it's the same as when I just added fragments again.


for details se my replace here if isRemoving. Also note I of cause had to disable the tryExecutingFragmentTransaction, so it would not wait for ever because of the bad fragment stuckin isRemoved

```
private fun executeFragmentTransaction(stateChange: StateChange, completionCallback: StateChanger.Callback) {
...
        var topFragment: BaseFragment<ViewModel>? = null
        for (newKey in newState) {
            @Suppress("UNCHECKED_CAST")
            val fragment: BaseFragment<ViewModel>? = fragmentManager.findFragmentByTag(newKey.fragmentTag) as? BaseFragment<ViewModel>
            if (newKey == stateChange.topNewState<Any>()) {
                if (fragment != null && !fragment.isRemoving) {
                    topFragment = fragment
                    attachOrShow(fragment, fragmentTransaction)
                } else {
                    val oldFragmentIsStuckRemoving = fragment != null
                    val newFragment: BaseFragment<ViewModel> = newKey.newFragment()
                    topFragment = newFragment
                    newFragment.bindViewModel(activity.backstackDelegate.getService(newKey, newKey.viewModelTag))
                    if (oldFragmentIsStuckRemoving) {
                        Log.d(TAG, "Fragment count: "+fragmentManager.fragments.size)
                        fragmentTransaction.replace(containerId, newFragment, newKey.fragmentTag)
                    } else {
                        fragmentTransaction.add(containerId, newFragment, newKey.fragmentTag)
                    }
                }
            } else {
                detachOrHide(fragment, fragmentTransaction)
            }
        }
        fragmentTransaction.commitNow() // had to be `now` in the sample, but you can probably use `allowingStateLoss()`
        completionCallback.stateChangeComplete()
        if (topFragment != null) {
            scheduleOnNavigationComplete(previousState, topFragment)
        } else {
            throw IllegalStateException("No top fragment")
        }
}
```

Do you know if Google reads to public bug-reports these days? Might it be worth reporting it? My guess is they'll dismiss it because they can't reproduce it, and its way to much work for me to make a tiny project that can reproduce it. Esp. because I might not be able to.

**Comment by Zhuinden** [comment]
> I tried it, it doesn't work well. It does replace the fragment, so there's seemingly no issue. But old replaced fragments don't get their onDestroy called before activity.onDestroy() and thus leaks.

I think this is most likely a bug inside MapFragment. A replaced fragment *should* eventually be destroyed once "all animations finish" (and `isRemoving` stops being, well, `isRemoving`).

The `replace` variant should work, I think I'll replace the new "SafeFragmentStateChanger" with that, just to ensure that it works fine. Nicer than waiting for the fragment transactions to complete...

----

> ```
>     java.lang.IllegalArgumentException: The provided offset value [1] was out of range: [-1; 1)
>         at com.zhuinden.simplestack.History.fromTop(History.java:75)
>         at dk.bnr.androidbooking.application.injection.MessageQueue.pushMessageToParent(MessageQueue.java:34)
> ```

I probably could have defined a better error message for this 🤔 but this just means you're trying to do `fromTop(1)` on a History that is `size=0`, therefore you can't get the `size-1`th element as it would be the `list.get(-1)`. So basically `ArrayIndexOutOfBoundsException`.

No i'm not sure why your history is 1-element size when you expect there to be a *parent* (a key underneath the current one).

**Comment by arberg** [comment]
If you have like 10-15 min for a teamviewer session I can show you. I think its a bit hard to decode from text-based communication what is going on. The History is wrong, I think there's a size 2 history, because it should be there, but the bug only happens after restarting my activity from the bad state, and there's some singletons involved, like backstack. My project is based on the MVVM example with dagger, in simple-stack.

It could be something about nested fragments, as the map-fragment is nested within the MainFragment. I don't changed the nesting of the mapfragment, or swap it, but still its a nested fragment.

**Comment by Zhuinden** [comment]
I'll only be able to TeamViewer today in a few hours from now, but feel free to add me on Skype in the meantime.

> The History is wrong, I think there's a size 2 history, because it should be there

It's definitely a size 1 history, but it's possible that it is size 1 because `onDestroy` of delegate calls `executePendingStateChange` which forces the state change to be deemed completed.

**Comment by Zhuinden** [comment]
As discussed,

1.) I have no idea why the *second* fragment stays `isRemoving()` if you do animations *while the Camera is zooming*

2.) the history was wrong because it was using a Backstack instance from a previous execution of the app, and changing it from `@Inject(Backstack backstack` to `@Inject(BackstackHolder` fixed it.

**Comment by arberg** [comment]
Thanks for the help and the tour of your code, it was quite interesting.

**Comment by Zhuinden** [comment]
@arberg Hey, this might be relevant to why your Fragment was stuck in `isRemoving`: https://issuetracker.google.com/issues/116257087

**Comment by arberg** [comment]
Thanks a lot for forwarding that to me Zhuinden, that was kind of you. 

Indeed it does look like that could very well be the issue related to the stuck fragments during Google map animations.

**Comment by Zhuinden** [comment]
I hear that overall the magic trick is to put the Fragment inside a `androidx.fragment.app.FragmentContainerView` instead of a FrameLayout or similar regular container.

**Comment by arberg** [comment]
Hi, Its so cool you think of me and the bug after so long. I had a moment to try it now. It didn't help. It sounds like the FragmentContainerView is related to z-order handling, and indeed it did mess up some z-handling in the app in fragment transitions :) A view was suddenly over the fragment sliding, crazy. 

But for the issue with crashing if I don't postpone map updates til after the navigation complete, then it still crashes if I use FragmentContainerView and update google map, during fragment transition. I have mostly circumventing that issue, but I still see some other weird stuff, so I'm contemplating dropping fragments for self-managed implementation swapping views and managing transitions.

**Comment by Zhuinden** [comment]
> Hi, It's so cool you think of me and the bug after so long.

It's such an esoteric bug, I was hoping to see it fixed *somehow* 😉 

> I had a moment to try it now. It didn't help. It sounds like the FragmentContainerView is related to z-order handling, and indeed it did mess up some z-handling in the app in fragment transitions :) A view was suddenly over the fragment sliding, crazy.

Oh. Hm. Well I was not expecting that at all. 😞 They said that it makes sure that `android:animateLayoutChanges` is disabled for the fragments within the container, which did have some odd interaction with map fragments, but I guess this is a different problem then...

> so I'm contemplating dropping fragments for self-managed implementation swapping views and managing transitions.

What fragments do provide out of the box that people tend to use is the `onCreate/onStart/onStop/onDestroyView` callbacks, but a decent "proxy" for them is `onFinishInflate/onAttachedToWindow/onDetachedFromWindow`.

For swapping views, I recommend checking out this state changer: https://github.com/Zhuinden/simple-stack/blob/a1e8e3e99dda7375074ce8fe9f301cf15d604261/simple-stack-example-mvp-view/src/main/java/com/zhuinden/simplestackdemoexamplemvp/core/navigation/ViewStateChanger.kt#L19

**Comment by arberg** [comment]
Thx for the links, something like that might indeed be useful, if I'm switching to managing my own view-changes.
