### ISSUE TITLE
ScopedServices.HandlesBack doesn't match if the key is `ScopeKey.Child`, but not `ScopeKey`, and the explicit parent scope is defined by a previous key as well

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack#210]
Currently found this bug, which is disconcerting.

Apparently despite the tests for `findScopeForKey(key, ScopeLookupMode.EXPLICIT)`, this can somehow ***still*** fail to return the explicit scope registrations for that key, if the key has no scope registration on itself, but the previous key has also registered an explicit parent scope by the same name.

Which means that `dispatchBack()` doesn't find the explicit parent if the scope name is registered by the previous scope, if the scope is only `ScopeKey.Child`, but not `ScopeKey`.

Having a scope registration with `ScopeKey` solves this, as from the "node-wise" scope, a registration is found, and its explicit parent is evaluated based on its associated parent scopes.

Will fix ASAP, which is probably tomorrow.

**Comment by Zhuinden** [comment]
Fixed in https://github.com/Zhuinden/simple-stack/commit/781525c0d95d49ad0c13d286ca9c2ddb4f91125b

**Comment by Zhuinden** [comment]
@matejdro I encountered this while tinkering with `HandlesBack` + the explicit parent scoping mechanics you've outlined, so you might be affected by this.

I've released the fix in 2.2.1.

**Comment by matejdro** [comment]
Thanks. I did not use `HandlesBack`, so this did not affect me.
