### ISSUE TITLE
`startActivityForResult` analog

### ISSUE THREAD

**Issue by amitav13** [Zhuinden/simple-stack#218]
Hi,
My use case is as follows:

I have a home screen (say H), some other screen(O) and a form-fill flow of 3 screens (S1, S2, S3). The form-fill flow can be started from either H or O. The end result of form-fill flow (S1 -> S2 -> S3) is a `data class`, say `FormData`. On form submission on S3, I want to pass back the `FormData` generated to either H or O, whichever started the flow. I'd ideally like to also pass the data between S1, S2 and S3 (assuming it is lightweight parcelable data).

Is it possible to achieve this flow using a single activity?

**Comment by Zhuinden** [comment]
Hi!

Thanks for the question, I do intend to answer in depth, but this is actually being discussed in https://github.com/Zhuinden/simple-stack/issues/216

If you check the latest comment https://github.com/Zhuinden/simple-stack/issues/216#issuecomment-586393688, the intended current recommendation is to have a shared scoped (implicit or explicit (`ScopeKey` or `ScopeKey.Child`)) service, and you can retrieve the parent flow service at construction time of the child service using `serviceBinder.lookupService()`.

If you want, you can expose an interface from the child flow's service, implement it on the parent service, and register that parent service with `addAlias` by the name of that child interface.

That way the `lookup`of the child would get the interface and doesn't know exact type, only parent knows that it has to be registered as the child interface as well.

See the scoping example for more information, and ask any further questions if the explanation is unclear.

**Comment by Zhuinden** [comment]
You can check this example:

https://github.com/Zhuinden/simple-stack-tutorials/blob/1a4fb5175039f7e7ef3051491f109aa017360990/app/src/main/java/com/zhuinden/simplestacktutorials/steps/step_7/features/registration/RegistrationViewModel.kt#L12

But I will update the Repo to actually show how two flows can interact via `serviceBinder.lookupService`.

**Comment by Zhuinden** [comment]
@amitav13 have any of my propositions been helpful for your use-case so far?

**Comment by amitav13** [comment]
I was just checking on the feasibility of my use-case before going in on this library. Good to see that there are some potential solutions for it. Thanks!

**Comment by Zhuinden** [comment]
For future reference, I created a sample that shows how result passing can generally be done between screens: https://github.com/Zhuinden/simple-stack-tutorials/blob/f1ed762efe14a50dc615ebc073657056147a541c/app/src/main/java/com/zhuinden/simplestacktutorials/steps/step_8/features/form/FormViewModel.kt#L8

But the `getSavedState` trick would also work reliably in 2.2.5+.
