### ISSUE TITLE
Project doesn't sync in Studio

### ISSUE THREAD

**Issue by amitav13** [Zhuinden/simple-stack#219]
Hi,
I've cloned and imported the complete repo, and when it's trying to sync I'm hitting this error:

```
Failed to resolve: com.bluelinelabs:conductor:2.1.5-SNAPSHOT
Affected Modules: simple-stack-example-conductor-java
```

Here's my setup:
```
Android Studio 4.0 Beta 1
Build #AI-193.6494.35.40.6220182, built on February 20, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, Quick Notes, org.jetbrains.kotlin, com.mighty16.json.kotlin.class, com.vladsch.idea.multimarkdown, io.flutter, izhangzhihao.rainbow.brackets
```

This is on the `master` branch. 

Edit: Fixed it by removing the `SNAPSHOT` in the dep.

**Comment by Zhuinden** [comment]
Interesting that the snapshot has disappeared, it was at the time necessary due to a bug in 2.1.4's `setBackstack` method. But 2.1.5 took more than a year to come out stable. I'll just remove the `-SNAPSHOT` and it should work, thanks for the notice.
