### ISSUE TITLE
Koin integration sample

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack#227]
To be honest, I never saw a need for Koin. Their scoping is very similar to what Simple-Stack is doing, with the caveat that they don't offer lifecycle callbacks and state persistence (they expect you to use Jetpack ViewModel and SavedStateHandle to achieve it).

Theoretically if I were to expose providers from Koin, it wouldn't be too hard to channel those over into simple-stack, considering Koin is already a globally accessible singleton instance. So you see it from keys and is compatible with `DefaultServiceProvider.HasServices`.

People would love it, because people love Koin.

**Comment by paolovalerdi** [comment]
As a newbie, this would be very appreciated!

**Comment by Zhuinden** [comment]
Koin isn't really needed when using Simple-Stack.

If this ever happens, it would be as a separate sample, but not in this repository.

Technically it could also be a `community-sample` but I don't intend to add one, as it really is just funneling over Koin's `provider {}`s but if you're not opting into the Jetpack ecosystem, Simple-Stack's scoped services already handle this stuff anyway.
