### ISSUE TITLE
Multistack stack change with history

### ISSUE THREAD

**Issue by uvaysss** [Zhuinden/simple-stack#236]
Hi, I'm using your multistack implementation from sample, but having trouble by implementing some tricky navigation behavior. The case is that I need to navigate to a fragment that is in another stack. I'm trying to accomplish this by first selecting the stack and then setting history:

`Multistack.setSelectedStack(identifier)`
`Multistack.getSelectedStack().setHistory()`

But I'm getting an incorrect behavior, all the fragments from the history are shown at the same time. I tried to call 

`Multistack.executePendingStateChange()`

before setting the history, but the result is the same.

**Comment by Zhuinden** [comment]
> But I'm getting an incorrect behavior, all the fragments from the history are shown at the same time. 

That shouldn't happen as long as the keys are each `data class` (and therefore have a stable equals/hashCode/toString). 🤔 

Are all of your keys `data class`?

**Comment by uvaysss** [comment]
Yes, they are `data class`.

**Comment by uvaysss** [comment]
But I've noticed that if I make a delay before history change like `Handler.post {}` than it works correct.

**Comment by Zhuinden** [comment]
Oh, I should be calling `fragmentManager.executePendingTransactions()` on [the first line](https://github.com/Zhuinden/simple-stack/blob/01d719f03b85ee12f88ea12c967cde5154443e9b/samples/multistack-samples/simple-stack-example-multistack-fragment/src/main/java/com/zhuinden/simplestackdemomultistack/core/navigation/MultistackFragmentStateChanger.kt#L15), and then probably [apply the safety measures which is basically `Handler.post {}` that I also ended up adding to `simple-stack-extensions`](https://github.com/Zhuinden/simple-stack-extensions/commit/7ffba2e9a6e492385fdcd338c8d9c4c5b87efb14#diff-3aa54d4c950a8c260a29a2dee13fd5a7ab5ff92a0b9012b335508649b92cc57dR119)

Valid find, I'll update it accordingly.

**Comment by Zhuinden** [comment]
Thanks!

**Comment by uvaysss** [comment]
Thank you for your quick response!
