### ISSUE TITLE
Consider a way to connect a "child nested stack" to a "parent stack" similarly to `setParentComposition`

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack#239]
While multi-stack is not the focus of the library by default, if it were possible to integrate against Compose using actual composable functions instead of [externally stored state](https://github.com/Zhuinden/compose-simple-stack-experiment/blob/cf90542396708deedab0c749be24b8163b51217a/app/src/main/java/com/zhuinden/firstcomposeapp/MainActivity.kt#L19-L46) (see the behavior of OnBackPressedDispatcher for why this is actually potentially impossible without manually hijacking onBackPressed in Activity), then it would be possible to introduce a backstack at any "nesting level". After all, what needs to be propagated is back events and service lookups.

Although can you truly keep alive a child composition's "belongings" (read: scoped services / global services) in a retained scope? Not even Compose has figured this out without the use of Fragments to host ViewModelStores.

**Comment by Zhuinden** [comment]
Actually if I take my own simple-stack multi-stack sample as inspiration, as long as the children can hook themselves into "a parent" (eventually the global) scope's scoped services it'd get everything it needs 🤔

**Comment by Zhuinden** [comment]
Until this is resolved, see https://github.com/Zhuinden/simple-stack/issues/247#issuecomment-910227261 for more info

**Comment by matejdro** [comment]
What if we just pass all currently resolvable services to GlobalServices of the child backstack, when we create the child?

From what I can see, services are immutable, so this should technically work? Services are not enumerable at the moment, but we could add a method for that.

Only issue I can see is with `ScopedServices.Activated`, `ScopedServices.Registered` and `Bundleable` - those callbacks would be triggered twice (for the child and for the parent). Maybe we could add `suppressCallbacks` to `GlobalServices.Builder.addService` method?

**Comment by Zhuinden** [comment]
@matejdro i don't think that's a good idea. It actually makes more sense for the child to have its own "globals" and own scopes.

I think I overthought this and we could just expose something like `˙backstack.setParentBackstack()` and just alter the behavior of `lookupService()`/`canFindService()` to also check the parent if it's null in the current. Then there is no duplication of any sort between scopes.

**Comment by matejdro** [comment]
Considering #274, would it also make sense to have `backstack.setParentBackstack(backstack, scope)`?

**Comment by Zhuinden** [comment]
@matejdro I actually don't see how that would work 🤔  Although I do admit it raises the question of what happens if the one performing the lookup is not part of the top-most chain. Maybe passing in a scope tag is unavoidable.

**Comment by matejdro** [comment]
The way I see it working is:

1. Child performs `lookupService`/`lookupFromScope` normally
2. If service is not found, it starts looking into parent:

a) If `setParentBackstack` was set with explicit scope, it would search inside parent using `parent.lookupFromScope()`. 
b) Otherwise, it would search using `parent.lookupService()`

**Comment by Zhuinden** [comment]
I probably should have actually written the code for this like 2 months ago, huh

**Comment by matejdro** [comment]
This is how we do it at the moment: https://github.com/inovait/kotlinova/blob/611b9f9c2719e01583760b25df82e7d84d97bfc8/navigation/src/main/kotlin/si/inova/kotlinova/navigation/simplestack/ServiceInheritance.kt

When nested backstack is created, [registerParentBackstack() is called on its global services](https://github.com/inovait/kotlinova/blob/611b9f9c2719e01583760b25df82e7d84d97bfc8/navigation/src/main/kotlin/si/inova/kotlinova/navigation/simplestack/InjectedBackstackFactory.kt#L69). Then we use above linked `lookupFromScopeWithParentFallback`to lookup services.

**Comment by Zhuinden** [comment]
Added in 2.8.0. Please check if it solves your usecase.

**Comment by matejdro** [comment]
Can confirm, it solves my use case. Thanks!

**Comment by Zhuinden** [comment]
My plan is to add a new overload which is "propagateExplicit=true" which would search with explicit even in all the parents.

Not sure if it's important, but I feel it makes sense to have it.

I'm glad it solves your issue and sorry it took a bit long 😅
