### ISSUE TITLE
Jetpack Compose

### ISSUE THREAD

**Issue by matejdro** [Zhuinden/simple-stack#240]
Has there been any considerations on using simple-stack with Jetpack Compose? Would that even make any sense?

**Comment by Zhuinden** [comment]
Yes, there actually is a Compose integration in https://github.com/Zhuinden/simple-stack-compose-integration/ currently at 0.2.0

https://twitter.com/Zhuinden/status/1371961357554319365

Which is what handles when you're using only Composables. Whatever is your current superset of  screen abstraction is what you should use (so if you are using "custom views + compose" then stick with custom views and put Compose in a ComposeView, etc)

**Comment by Zhuinden** [comment]
I have added it to the end of the readme, thanks!

https://github.com/Zhuinden/simple-stack/commit/f3df575e9237a5a8c9b7f2c1ca4b18956d5a1ab7
