### ISSUE TITLE
Multiple stacks in each viewpager fragment

### ISSUE THREAD

**Issue by omkar-tenkale** [Zhuinden/simple-stack#252]
Aim is to emulate the instagram like functionallity

a viewpaer with bottom bar - 5 tabs

each viewpager fragment is a container and has its own simple-stack navigator

So at any time states can be

A-B  |  B-C | C-A-B-A-C  | D-A-B  | E-F 

Each viewpager page has its own stack and user can switch between them with bottombar easily no stack will be reset after switching

Instagram navigation works similarly

Can simple-stack help me achieve this?

**Comment by Zhuinden** [comment]
Hey hey, it's a bit tricky, but yes, refer to the multi-stack example below

https://github.com/Zhuinden/simple-stack/tree/df0308469080613888a695c3b66a8373e54e3f45/samples/multistack-samples/simple-stack-example-multistack-nested-fragment/src/main/java/com/zhuinden/simplestackbottomnavfragmentexample
