### ISSUE TITLE
Tried to build your project - error

### ISSUE THREAD

**Issue by nextdimension** [Zhuinden/simple-stack#27]
I get some error about auto generated types when I try to build it. Didn't investigate further.

**Comment by Zhuinden** [comment]
.....i replaced auto-parcel with paperparcel without checking if it'd work.

I guess I should have investigated further, lol.

**Comment by Zhuinden** [comment]
Reverted commit with https://github.com/Zhuinden/simple-stack/commit/d4b862103b1f0dc41928d9dda60ef02abd802265 and it should work now
