### ISSUE TITLE
Handle process death.

### ISSUE THREAD

**Issue by CodyEngel** [Zhuinden/simple-stack#34]
Hey just pulled down simple-stack and wanted to play around with it. Pulled down the repo and tried out simple-stack-example-services but noticed that the stack doesn't persist after process death.

Steps to reproduce:
1. Open simple-stack-example-services
2. Click "Go to B"
3. Put the app in the background.
4. Kill the app through the multitasking pane
5. Open simple-stack-example-services, notice that you are no longer on B and are instead back at the start.

**Comment by Zhuinden** [comment]
You killed it through the multi-tasking pane, which means you've cleared the task, essentially killing the Activity, destroying its record and its persisted state.

If you put the app in background, and use the "terminate" button in Android Studio in the bottom left corner on the Android Monitor tab, then it works as intended (which is the same behavior as low memory condition, you can try https://play.google.com/store/apps/details?id=me.empirical.android.application.fillmemory&hl=en ).

**Comment by Zhuinden** [comment]
Did that answer the question?

**Comment by jamolkhon** [comment]
I'm experiencing this problem at the moment while trying to test my changes to FragmentStateChanger (#193)

However, I'm using the terminate button at step 4. At step 5 I'm opening the app from multitasking pane.

**Comment by jamolkhon** [comment]
My initial thought was that the problem is due to a misconfiguration by me (like #150). But I was able to reproduce the same problem with the simple-stack-example-basic-java-fragment sample too.

**Comment by Zhuinden** [comment]
@jamolkhon if you clear the task, then the Activity is killed along with all its fragments.

When I mention "process death", it refers to low memory condition.

See https://stackoverflow.com/questions/49046773/singleton-object-becomes-null-after-app-is-resumed/49107399#49107399

**Comment by jamolkhon** [comment]
This is what I did.
> If you put the app in background, and use the "terminate" button in Android Studio in the bottom left corner on the Android Monitor tab, then it works as intended

Does the task get cleared when the app is in the background and I press terminate button in Android Studio?

**Comment by Zhuinden** [comment]
> Does the task get cleared when the app is in the background and I press terminate button in Android Studio?

That's actually different, terminate in background is "process kill" but as it had been put to background, it has active records and the same phenomenon as a low memory process death. **This case is supported by Simple-Stack and you should be restored to exactly where you were**. 

Task clear only happens when you go to Recents screen then swipe your app away (on some phones up on some others right), in this case your Activity is killed along with the records and therefore so is the Backstack.

I shouldn't have reopened this, this is a very old issue and the lib works fine in these scenarios. 

Also I think the original `services` sample this one refers to has long been killed, too :smile: and replaced by ScopedServices api

**Comment by jamolkhon** [comment]
I'm honestly truly confused. Probably my previous comment was not clear.

Should an app properly using SimpleStack be able restore it's backstack by being put on background via Home button pressing and terminating via Android Studio?

If yes, I'm doing exactly that. But the behaves as if I'm opening it for the first time.

If no, then it's my bad not understanding.

**Comment by Zhuinden** [comment]
> Should an app properly using SimpleStack be able restore it's backstack by being put on background via Home button pressing and terminating via Android Studio?

Yes. 

And if it behaves as if it were the first time then there might be someone replacing the first fragment outside of the FragmentStateChanger. 

Alternately, check for crash logs. :thinking_face:
