### ISSUE TITLE
Add a way to override getting previousView from DefaultStateChanger

### ISSUE THREAD

**Issue by gumil** [Zhuinden/simple-stack#36]
In some use case like showing a dialog screen (cause the previous view is still visible when the latest view is pushed), the previousView is not removed from the container. In this case when navigating back, the previousView is the last child of container.

**Comment by Zhuinden** [comment]
I can't really provide a means beyond you handling it in a custom `ViewChangeHandler`, that's what does the `container.removeView(previousView)`.

**Comment by Zhuinden** [comment]
`GetPreviousViewStrategy` in 1.6.1
