### ISSUE TITLE
Navigation within multistack activity.

### ISSUE THREAD

**Issue by avonil** [Zhuinden/simple-stack#43]
Hi, 

I did not find another way to contact you, so I decided to create an issue. 
I have single activity app with implemented multistack feature. 

In my app, I have SearchResultView which is accessible from two different places. From HomeView and from SearchView. SearchView and SearchResultView are in the same stack. SearchView is set as the default view for this particular stack( SearchStack ) . HomeView is placed as the default view for HomeStack. 

I am using your default StackChanger implementation for multistack example where  I have added view change animation. 

The problem I have is when I am changing the view from HomeView ( added to HomeStack) to the SearchResultView ( added to SearchStack). SearchResultView is not a default view for his stack so when the animation is performing I firstly can see SearchView ( default for his stack) and after that SearchResultView is showing on the screen. 

The question is how to change view from HomeView ( HomeStack) to SearchResultView ( SearchStack with SearchView as default) without showing default view for SeachStack ( SearchView )

Thanks for help
Best
Damian

**Comment by Zhuinden** [comment]
Hi, thanks for reaching out!

If you are using the [MultiStack](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack-example-multistack/src/main/java/com/zhuinden/simplestackdemomultistack/util/Multistack.java) class from the `simple-stack-example-multistack` along with a custom state changer like in that example (the `MainActivity`), then it seems to me that calling `multistack.setSelectedStack(StackType.values()[itemIndex].name());` gets evaluated in the state changer [based on the previously shown view](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack-example-multistack/src/main/java/com/zhuinden/simplestackdemomultistack/application/MainActivity.java#L186-L191) - what stack it belonged to, and what kind of animation it should show.

`setStateChanger()` should call an initialize state change (so previous state will be empty list), but it should initialize to the previously saved state as new state, and NOT the default key.

----------

Meaning in the example, going from MAIL to CLOUDSYNC will show a state change of `[[], [CloudSync, Another]]` - but this means that you *are* supposed to initialize to the top state of the other stack, without initializing to CloudSync first.

So I don't seem to be reproducing the two-step initialization and would need to see more code to know what's up.

**Comment by avonil** [comment]
Hi, thanks for fast replay. 

Base on your answer I think I found the proper solution, but I will try to explain it better to you. 

Here is my initialization code: 

`private fun initMultistack(savedInstanceState: Bundle?) {
        multistack = Multistack()

        multistack!!.add(HOME.name, BackstackDelegate(null))
        multistack!!.add(SEARCH.name, BackstackDelegate(null))
        multistack!!.add(CONTACT.name, BackstackDelegate(null))
        multistack!!.add(EXTRA.name, BackstackDelegate(null))
        multistack!!.add(PROFILE.name, BackstackDelegate(null))

        val nonConfigurationInstance: Multistack.NonConfigurationInstance? = lastCustomNonConfigurationInstance as? Multistack.NonConfigurationInstance

        multistack!!.onCreate(savedInstanceState)

        multistack!!.onCreate(HOME.name, savedInstanceState, nonConfigurationInstance, HomeKey())
        multistack!!.onCreate(SEARCH.name, savedInstanceState, nonConfigurationInstance, SearchKey())
        multistack!!.onCreate(CONTACT.name, savedInstanceState, nonConfigurationInstance, ContactKey())
        multistack!!.onCreate(EXTRA.name, savedInstanceState, nonConfigurationInstance, ExtraKey())
        multistack!!.onCreate(PROFILE.name, savedInstanceState, nonConfigurationInstance, ProfileKey())
    }`

My previous solution was: 
`Backstack.getKey<Key>(context).selectDelegate(context).backstack.goTo(newKey)`

Currently I have something like this: 
`fun ViewGroup.goTo(newKey: Key, animationType: ExtradomAnimationUtils.AnimationType, stackIdentifier: String? = null) {
    newKey.animationType = animationType
    newKey.parentStackIdentifier = stackIdentifier ?: Backstack.getKey<Key>(context).stackIdentifier()
    Backstack.getKey<Key>(context).selectDelegate(context).backstack.goTo(newKey)
})`

Github formatting is not working well for this part of code. 
Here is pastebin url: https://pastebin.com/8WELEq6J 

My solution base on changing stack identifier for a particular key on the fly. It means when I want to reach out SearchResultView from HomeView the stack identifier for SearchResultKey is HOME.name, but when I want to reach out SearchResultView from SearchView ( default view for SEARCH.name stack) then I returning default stack identifier for SearchResultKey. 

I found one problem with my solution. I have two different SearchResultView in the application. One in HOME.name stack and one in SEARCH.name stack. 

Here is the rest of code for better understanding: https://pastebin.com/3bRB45Y7

**Comment by Zhuinden** [comment]
Consider making `multistack` be `lateinit`, that way you don't need to write the `!!`s.

> I found one problem with my solution. I have two different SearchResultView in the application. One in HOME.name stack and one in SEARCH.name stack.

This should not be a problem as long as `SearchResultKey` knows what stack it is in, and that `equals()` is not true for the two keys of the two views of the same type.

-----

However, I've been thinking about this but the API doesn't really seem to allow calling `setStateChanger()`  on a BackstackDelegate (or a BackstackManager) without calling an `initialize` state change. I wonder if you really do need to jump between the stacks in order to navigate to the SearchResultView?

**Comment by avonil** [comment]
Maybe I don't have to change stack but I don't have any idea how to do that. My goal is to go to the SearchResultView but with current implementation it is connected with SEARCH.name stack. 
Do you have any idea?

**Comment by Zhuinden** [comment]
@avonil the simple solution (I do not know if your design requires otherwise) would be to give the selected stack of `SearchResultView` as an input parameter for the constructor so that you have a "parentStack" instead of directly binding the view to only one given stack.

**Comment by avonil** [comment]
Great. My solution base on the same concept. Thanks for help! :)

**Comment by Zhuinden** [comment]
If you run into any issues, feel free to reach out!

**Comment by Zhuinden** [comment]
It's probably been a while and it's not relevant at this point, but I've updated the Multistack sample as per `simple-stack 2.0` which makes it more convenient to use than with the original BackstackDelegate-based version.

https://github.com/Zhuinden/simple-stack/blob/f28fcae66287dbb92faefdc905cd2901dd3e7e8d/simple-stack-example-multistack-view/src/main/java/com/zhuinden/simplestackdemomultistack/core/navigation/Multistack.kt
