### ISSUE TITLE
How to use simple-stack with objects parceled through johncarl81/parceler?

### ISSUE THREAD

**Issue by dev-JE02** [Zhuinden/simple-stack#52]
We have an existing project we need to incorporate the library in. The problem is, I would like to have put objects in the Keys. These objects does not implement Parcelable and I don't think I can refactor all of them into using Auto-Parcel as it is a pretty big project. Is there a way around it? Or how can I use simple-stack without relying on auto-parcel?

**Comment by Zhuinden** [comment]
If you're using BackstackDelegate, then you need to call

    BackstackDelegate backstackDelegate = new BackstackDelegate(null);
    backstackDelegate.setKeyParceler(new ParcelerParcelationStrategy());
    backstackDelegate.onCreate(...);
    backstackDelegate.registerForLifecycleCallbacks(this);

with custom views it would be

    Navigator.configure()
          .setKeyParceler(new ParcelerParcelationStrategy())
          .setStateChanger(...)
          .install(...)

Where `ParcelerParcelationStrategy` is

``` java
public class ParcelerParcelationStrategy
        implements KeyParceler {
    @Override
    public Parcelable toParcelable(Object object) {
        return Parcels.wrap(object);
    }

    @Override
    public Object fromParcelable(Parcelable parcelable) {
        return Parcels.unwrap(parcelable);
    }
}
```

**Comment by dev-JE02** [comment]
Thank you very much!
