### ISSUE TITLE
How do you replace the current top item in the backstack?

### ISSUE THREAD

**Issue by dev-JE02** [Zhuinden/simple-stack#57]
I have 2 fragments and the operation would be like this

fragmentA opens fragmentB
fragmentB, makes an operation
fragmentB, finishes or closes and passes data to another instance of fragmentA
fragmentA(old) will be closed and replaced with fragmentA(new) to imitate that the view has been updated through the use of fragmentB

Right now, I'm thinking of using this:
```
Backstack backstack = backstackDelegate.getBackstack(); // lifecycle integration
backstack.setHistory(HistoryBuilder.single([key of fragmentA(new)]), StateChange.REPLACE);
```
But I'm afraid that the whole backstack will be cleared when I do

**Comment by Zhuinden** [comment]
The original Flow did have a `replaceTop()` operator but for whatever reason I never had a need for it even though we've used it in multiple projects, so it's not a "first-class" method in `simple-stack`.

But the following would do exactly that:

``` java
Backstack backstack = backstackDelegate.getBackstack(); // lifecycle integration
backstack.setHistory(HistoryBuilder.from(backstack)
                                    .removeLast()
                                    .add([key of fragmentA(new)]).build(), 
                                     StateChange.REPLACE);
```

You might also find [`removeUntil()`](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack/src/test/java/com/zhuinden/simplestack/HistoryBuilderTest.java#L59) helpful on the `HistoryBuilder`.

--------

Then again, this use-case:

> fragmentB, finishes or closes and passes data to another instance of fragmentA
>
> fragmentA(old) will be closed and replaced with fragmentA(new) to imitate that the view has been updated through the use of fragmentB

I did run into this and unless you want to update the arguments bundle, you can use a `MessageQueue` of sorts as you can see in the [mvvm-sample](https://github.com/Zhuinden/simple-stack/blob/1baf4300c3482a0e6660e1ad25d2be00ff24e800/simple-stack-example-mvvm-fragments/src/main/java/com/zhuinden/simplestackexamplemvvm/application/injection/MessageQueue.java) which you can see is used [here](https://github.com/Zhuinden/simple-stack/blob/1baf4300c3482a0e6660e1ad25d2be00ff24e800/simple-stack-example-mvvm-fragments/src/main/java/com/zhuinden/simplestackexamplemvvm/presentation/paths/addedittask/AddEditTaskViewModel.java#L132-L137)

**Comment by dev-JE02** [comment]
Thank you very much! I'll try the `MessageQueue` solution when I have more time on my hands

**Comment by dev-JE02** [comment]
Sorry another question, how do I get the currently displayed fragment using BackStack?

**Comment by Zhuinden** [comment]
uh, that is the responsibility of the StateChanger. Which in my case tends to be the Activity itself.

So to make the Backstack show a given fragment, what you need to do is handle the transition between the previous state and the new state, in this case using the `FragmentTransaction`'s API. Without calling `addToBackStack()` on it, because that changes fragment behavior. 

For example, if you only want to show the top fragment, then it is a good choice to [detach the ones that are not visible, attach the top, and add it if it's not even in the fragment manager yet.](https://github.com/Zhuinden/simple-stack/blob/1baf4300c3482a0e6660e1ad25d2be00ff24e800/simple-stack-example-mvp-fragments/src/main/java/com/zhuinden/simplestackdemoexamplefragments/util/FragmentStateChanger.java#L32-L59)

``` java
        for(Key oldKey : stateChange.<Key>getPreviousState()) {
            Fragment fragment = fragmentManager.findFragmentByTag(oldKey.getFragmentTag());
            if(fragment != null) { // already added
                if(!stateChange.getNewState().contains(oldKey)) {
                    fragmentTransaction.remove(fragment); // no longer exists
                } else if(!fragment.isDetached()) {
                    fragmentTransaction.detach(fragment); // it will not be the new top so it can be detached
                }
            }
        }
```

and

``` java
        for(Key newKey : stateChange.<Key>getNewState()) {
            Fragment fragment = fragmentManager.findFragmentByTag(newKey.getFragmentTag());
            if(newKey.equals(stateChange.topNewState())) { // if is top
                if(fragment != null) {
                    if(fragment.isDetached()) {
                        fragmentTransaction.attach(fragment); // then if exists and is detached, attach
                    }
                } else {
                    fragment = newKey.newFragment(); // is not added, so add it
                    fragmentTransaction.add(containerId, fragment, newKey.getFragmentTag());
                }
            } else {
                if(fragment != null && !fragment.isDetached()) { // not top - should be detached
                    fragmentTransaction.detach(fragment);
                }
            }
        }
```

**Comment by dev-JE02** [comment]
Thank you very much for your help

**Comment by Zhuinden** [comment]
@dev-JE02 I've just checked this question again and I think I might have answered the wrong question?

The answer to checking the current top is just `backstack.top()`, then you can access the fragment tag and use `findFragmentByTag()` to get the fragment.
