### ISSUE TITLE
auto-value annotationProcessor configuration issue

### ISSUE THREAD

**Issue by jshvarts** [Zhuinden/simple-stack#67]
I tried building the project with `./gradlew assembleDebug` and getting:

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':simple-stack-example-sharedelement-fragment:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - auto-value-1.2.jar (com.google.auto.value:auto-value:1.2)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

The annotationProcessor is already in simple-stack-example-sharedelement-fragment/build.gradle

**Comment by Zhuinden** [comment]
What a silly bug :smile: thanks for the report, apparently updating to `auto-value 1.4.2` fixes the issue.

https://github.com/Zhuinden/simple-stack/commit/f38d0d9ce74ae9808bbaa50ac465ccd2309b47a4 and https://github.com/Zhuinden/simple-stack/commit/556f1704d1e1f02c0628969bac8069f284bf3ca3

**Comment by jshvarts** [comment]
Good to know! Thanks
