### ISSUE TITLE
Thought about obfuscation

### ISSUE THREAD

**Issue by Wahyd** [Zhuinden/simple-stack#71]
In your kotlin example you have

override fun toString(): String = javaClass.name 

Could we have an issue with ProGuard with this ? If yes, How can we avoid this ?

Thanks in advance

**Comment by Zhuinden** [comment]
That actually works, because it's `name` and not `simpleName`.

Even if package and class is renamed, all that matters is that the same class refers to the same class. And even after proguard, the `name` (fully qualified name) is unique.

Technically I only needed that because no-field data classes are not supported in Kotlin. AutoValue used to handle this case for me in Java. -_-

**Comment by Wahyd** [comment]
Oh ! Quick answer ! Thanks

I'll maybe try with a data class then

**Comment by Zhuinden** [comment]
@Wahyd you can see the "tricky example" [here](https://github.com/Zhuinden/simple-stack/blob/e45bfacb3f55c95e7385d5991f4353109fe12840/simple-stack-example-kotlin/src/main/kotlin/com/zhuinden/simplestackexamplekotlin/DashboardKey.kt#L10-L13).

I actually didn't come up with it, but it was a decent idea

**Comment by Wahyd** [comment]
@Zhuinden Actually when i try with "DashboardKey::javaClass.name" i have the String "javaClass" tag name for all my keys i use DashboardKey::class.java.name

**Comment by Zhuinden** [comment]
... Wow that's super strange, I kinda thought it's a shorthand but I guess not.

I'll fix this, thanks for reporting

**Comment by Zhuinden** [comment]
I now use ::class.java.name everywhere. In fact I did the change 9 days ago, just forgot to reply. Thanks!

**Comment by Zhuinden** [comment]
Anyways, Simple-Stack does not internally use reflection, only the samples use `toString` and sometimes `getName()` for fragment tag. This can be anything else though, but not part of the library.

If you don't use `getSimpleName()` for tags, you're generally fine.

**Comment by Wahyd** [comment]
Your welcome :)
