### ISSUE TITLE
goTo() is very slow

### ISSUE THREAD

**Issue by marc97** [Zhuinden/simple-stack#74]
The library is probably doing too much work when this method is called because is really slow. With a today's powerful hardware it is a little bit noticeable, but if not it is extremely slow.

**Comment by Zhuinden** [comment]
Technically it creates the previous state, the new state, and the StateChange which has the two lists.

Shouldn't be super-slow though. Do you have any profiling data to indicate that that is the source of the issue? If you have a history that is like, 50 items or so then it could be the arraylists internally, but it seems unlikely...

**Comment by Zhuinden** [comment]
Really though, if you show a screenshot that verifies that it is indeed `backstack.goTo()` that slows things down, I'll look into it.

**Comment by Zhuinden** [comment]
There is nothing here for me to go on. :|

I mean I could replace adding items to a list with `System.arrayCopy` but I'm not going to do that unless it's verified that this is a bottleneck.

Please profile the code and see if it really is the internals of `goTo` that slows things down and not just your StateChanger.
