### ISSUE TITLE
Make API public for obtaining Activity from the Context in a Custom View

### ISSUE THREAD

**Issue by btrautmann** [Zhuinden/simple-stack#75]
Here's a snippet of sample code from within a custom `ViewGroup` (I'm attempting a single `Activity` zero `Fragment` approach). I'd like to show a `DialogFragment`:

```
TextInputDialogBuilder()
                // ... builder pattern setters to set up the DialogFragment
                .build().show(((MainActivity)getContext()).getSupportFragmentManager(), "dialogTag");
```

This throws a `ClassCastException` because `getContext()` returns your `KeyContextWrapper`. I'm wondering what a good approach would be to doing things like this where you need your `Activity`s `Context`. If you think it's worth it, I might be willing to create a small sample as part of the repo.

**Comment by btrautmann** [comment]
For the record, something like _this_ works:

```
.build().show(ContextHelper.getActivity(getContext()).getSupportFragmentManager(), "dialogTag");
```

where `ContextHelper#getActivity(Context)` is:

```
    public static FragmentActivity getActivity(Context baseContext) {
        Context context = baseContext;
        while (context instanceof ContextWrapper) {
            if (context instanceof FragmentActivity) {
                return (FragmentActivity) context;
            }
            context = ((ContextWrapper) context).getBaseContext();
        }
        return null;
    }
```

But that has the downside of potentially returning null, and it doesn't seem like the right way to do things as it involves `while`-looping through `Context`s

**Comment by btrautmann** [comment]
Actually this looks like what you do in `Navigator#findActivity(Context)`

```
    private static Activity findActivity(Context context) {
        if(context instanceof Activity) {
            return (Activity) context;
        } else {
            ContextWrapper contextWrapper = (ContextWrapper) context;
            Context baseContext = contextWrapper.getBaseContext();
            if(baseContext == null) {
                throw new IllegalStateException("Activity was not found as base context of view!");
            }
            return findActivity(baseContext);
        }
    }
```

...although you avoid the NPE by throwing if null. Is this what you'd recommend doing for showing a `DialogFragment` from within the `ViewGroup`?

**Comment by Zhuinden** [comment]
In the predecessor of Simple-Stack which was called `Flowless`, I had an `ActivityUtils` class had the method `ActivityUtils.getActivity(Context)` which did exactly what `findActivity` does both in your case and in my case.

What I like to do lately personally is that if I have a single-activity (although it is possible with a `BaseActivity` too in which case you'd do `public <T extends BaseActivity> T`:

``` java

public class MainActivity
        extends AppCompatActivity {
    private static final String TAG = "MainActivity";

    @SuppressLint("WrongConstant")
    public static MainActivity get(Context context) {
        // noinspection ResourceType
        return (MainActivity)context.getSystemService(TAG);
    }

    @Override
    public Object getSystemService(@NonNull String name) {
        if(TAG.equals(name)) {
            return this;
        }
        return super.getSystemService(name);
    }
```

Then via any Context that has `MainActivity` in its base, you can do:

    MainActivity activity = MainActivity.get(view.getContext());

----

But the BaseContext-based look-up works too.

**Comment by btrautmann** [comment]
Thanks for the quick answer! I think you just both answered the question and consequently helped me understand Mortar, haha. Thanks!

I've seen you a lot on reddit and have learned a lot from you, so I appreciate it. I really want to implement a single activity app but just can't seem to make it work as easily as an activity-per-screen approach, probably because I need to learn dependency-injection better to make a lot of things work the way I picture them working when I start down the views-as-modules road. Anyway, just ranting. Thanks for all you do for the community.

**Comment by Zhuinden** [comment]
The tricky thing with views imo is:

- making something survive across config change

-  state persistence in a reasonable way down the hierarchy without having to override `Parcelable onSaveInstanceState()`.

I have this `Bundleable` interface, but it's kinda DIY to get the StateBundle from child views. I always envied how Conductor and Fragments auto-manage this stuff. 

-----

While I do think in *most* cases, single-activity is what represents the application properly (as activity is process entry point which can show UI), but technically it is possible to have multiple activities with each of them owning a BackstackDelegate or a Navigator.

So while I definitely dislike having 1 activity / screen with zero fragments/compound views, I think the hybrid of M activity + N customviews/fragments can make sense too. The built-in intent resolution scheme does help after all. (But then you need to use Activity-level up navigation and settings up tasks :p)

*Random fact: Back a while ago I thought to myself, "the operators are there, people can make their own `goUp()` if they need it" - would you have thought that `Up` navigation is rather oddly defined, and actually pretty  complex if you go deep into it? There are about 10 unit tests to verify edge cases just to make sure, `goUpChain()` was super tricky.*

-----

I had never really considered it but it makes sense to make `findActivity` in Navigator public, so I think I'll do that.

**Comment by Zhuinden** [comment]
`compile 'com.github.Zhuinden:simple-stack:1.8.1'` has this now, with `Navigator.findActivity(Context)`. :+1:
