### ISSUE TITLE
Why force to use auto-parcel?

### ISSUE THREAD

**Issue by LinArcX** [Zhuinden/simple-stack#76]
Hi @Zhuinden and thanks for this greate job. I follow your instructions in [this awesome page](https://github.com/Zhuinden/simple-stack/wiki/7.-Putting-it-all-together-into-a-view-based-setup). every thing is ok until i want to add auto-parcel library.
I send an issue for @frankiesardo and [report the problem](https://github.com/frankiesardo/auto-parcel/issues/55).
But my question is:
Why you force to use auto-parcel in custom views?
We know that this library does not have any update for about 2 years.
Is it possible to use another option instead of auto-parcel?

**Comment by Zhuinden** [comment]
Jake Wharton recommends `auto-value-parcel`, and I've been recommended `PaperParcel` by its author.

The Kotlin samples use `PaperParcel`, and I forgot to update the wiki to reflect this.

The `mvvm-fragments` sample (which is one of the newer ones) and the `basic-fragments` sample (which is even newer as it was just updated) use the [following setup](https://github.com/Zhuinden/simple-stack/blob/8edd0c80e2887c429fc2dede5f3c5607a7e2a47d/simple-stack-example-mvvm-fragments/build.gradle#L69-L72):

```
    compileOnly "com.google.auto.value:auto-value:1.4.1"
    annotationProcessor "com.google.auto.value:auto-value:1.4.1"
    implementation 'nz.bradcampbell:paperparcel:2.0.4'
    annotationProcessor 'nz.bradcampbell:paperparcel-compiler:2.0.4'
```

In this case, the `com/google/auto/value` isn't needed either.

So I'll update the wiki :smile:

**Comment by Zhuinden** [comment]
Actually, I've updated it right now.

**Comment by LinArcX** [comment]
Greate job!
Thanks a lot.
