### ISSUE TITLE
Remove transition  when use removeUntil(KeyToGoTo.create());

### ISSUE THREAD

**Issue by LinArcX** [Zhuinden/simple-stack#78]
Hello. look at thie scenario:
I create a bottomNavigationView and put 3 item in it. i called them: "fatherItems". and first fatherItem is "RootFatherItem".
In fatherItem1, user can go to deeper hierarchy like childItem1, childItem2 and ...
in fatherItem2 something similar may happen.
I want this behaviour:
When user go to FatherItems, all prevouis childItems remove from backstack and when press back button key, go to RootFatherItem. i used code below to achieve this goal:
```
backstack.setHistory(HistoryBuilder.from(backstack)
                                   .removeUntil(KeyToGoTo.create())
                                   .build(), 
                     Direction.BACKWARD);
```
But An unconventional behavior was seen. when i want to go back from FatherItem2 to FatherItem1, all childItems in FatherItem1 shows and i can see the view change animation:
<a href="http://uupload.ir/view/amlk_vokoscreen-2018-02-06_15-54-04.gif" target="_blank"><img src="http://uupload.ir/files/amlk_vokoscreen-2018-02-06_15-54-04_thumb.gif" border="0" alt="آپلود عکس" /></a>
i want to jump quickly without seeing any childItems.
Any idea?

**Comment by Zhuinden** [comment]
I think if you use `Direction.REPLACE` you'll get exactly that :+1:

**Comment by LinArcX** [comment]
No change happen:
```
backstack.setHistory(HistoryBuilder.from(backstack)
                                .removeUntil(rootKey)
                                .build(),
                        StateChange.REPLACE);
```

**Comment by Zhuinden** [comment]
...so I see you are most likely using `Navigator` with `StateKey`s and `SegueViewChangeHandler`, correct?

The tricky thing here is that in that case, what you are experience is possible **only** if you are somehow executing a *second* state change as well.

``` java
BaseKey rootKey = (BaseKey) Navigator.getBackstack(this).getInitialKeys().get(0);
backstack.setHistory(HistoryBuilder.from(backstack)
                                .removeUntil(rootKey)
                                .build(),
                        StateChange.REPLACE);
```

this code would trigger a StateChange of `[Home,History, Settings] -> [Home]`

So I think you are also calling `backstack.goBack()` above `backstack.setHistory()`, which would enqueue `[Home, History, Settings] -> [Home, History] -> [Home]` which *would* result in the animation you see here.

**Comment by LinArcX** [comment]
Yes. i use: Navigator with StateKeys and SegueViewChangeHandler.

> So I think you are also calling backstack.goBack() above backstack.setHistory()
No. i don't call that function at all.

**Comment by Zhuinden** [comment]
Do you by chance have a custom StateChanger, or do you use the default?

**Comment by Zhuinden** [comment]
If that doesn't happen, I'll gladly look at it if the project is something you can share on github.

**Comment by Zhuinden** [comment]
@LinArcX 

> So I think you are also calling backstack.goBack() above backstack.setHistory(), which would enqueue [Home, History, Settings] -> [Home, History] -> [Home] which would result in the animation you see here.

As provided in email, current complete code is:

``` java
    @Override
    public void onBackPressed() {
        if (Navigator.onBackPressed(this)) { // <--- !!
            Backstack backstack = Navigator.getBackstack(this);
            BaseKey currentKey = (BaseKey) Navigator.getBackstack(this).top();
            BaseKey rootKey = (BaseKey) Navigator.getBackstack(this).getInitialKeys().get(0);

            if (currentKey.isFather()) {
                navigation.setSelectedItemId(R.id.navigation_translate);
                backstack.setHistory(HistoryBuilder.from(backstack) // <-- !!
                                .removeUntil(rootKey)
                                .build(),
                        StateChange.REPLACE);
            } else {
                Navigator.getBackstack(this).goBack();
            }
        } else {
            super.onBackPressed();
        }
    }
```

The tricky thing is that `Navigator.onBackPressed()` was designed so that you don't need to remember to call something like `Navigator.getBackstack(this).goBack()` manually, because that's a bit tricky to remember.

So this is implementation of `Navigator.onBackPressed()`:

``` java
    public static boolean onBackPressed(Context context) {
        return getBackstack(context).goBack();
    }
```

So you **were** calling `goBack()` before `setHistory()`.

Following code should work:

``` java
    @Override
    public void onBackPressed() {
        Backstack backstack = Navigator.getBackstack(this);
        BaseKey currentKey = (BaseKey) Navigator.getBackstack(this).top();
        BaseKey rootKey = (BaseKey) Navigator.getBackstack(this).getInitialKeys().get(0);

        if (currentKey.isFather()) {
            navigation.setSelectedItemId(R.id.navigation_translate);
            backstack.setHistory(HistoryBuilder.from(backstack)
                            .removeUntil(rootKey)
                            .build(),
                    StateChange.REPLACE);
        } else {
            if(!Navigator.onBackPressed(this)) {
                super.onBackPressed();
            }
        }
    }

**Comment by LinArcX** [comment]
Thanks so much for your help :sparkling_heart:

**Comment by Zhuinden** [comment]
Glad I could help :D
