### ISSUE TITLE
Handle multistack with Navigator

### ISSUE THREAD

**Issue by LinArcX** [Zhuinden/simple-stack#79]
Hello. I have a simple application that contain a bottomNavigationView.
In each tab, i want to manage backStack Individually.
I see your `multistack-example` project in:
https://github.com/Zhuinden/simple-stack/tree/master/simple-stack-example-multistack
But in my project, i use Navigator and I'm so curious to know how to implement multistack with naviagator.
in your example there are some limitations(or problems, maybe :) ):
For example, every time i add new feature to app(that contain a *key class) i have to change main activity. 
```
    @Override
    public void onCreate(Bundle savedInstanceState) {
        this.multistack = new Multistack();
        multistack.add(TRANSLATE.name(), new BackstackDelegate(null));
        multistack.add(OTHER.name(), new BackstackDelegate(null));
        ...
        Multistack.NonConfigurationInstance nonConfigurationInstance = (Multistack.NonConfigurationInstance) getLastCustomNonConfigurationInstance();

        multistack.onCreate(savedInstanceState);
        multistack.onCreate(TRANSLATE.name(), savedInstanceState, nonConfigurationInstance, TranslateKey.create());
        multistack.onCreate(OTHER.name(), savedInstanceState, nonConfigurationInstance, OtherKey.create());
        ...
}
```
and add it to `multistack.onCreate..` method. Suppose i have 20 *key class.
Should i come back every time to mainActivity and add *keys to multistack?
How to implement multiStack with Navigator?

**Comment by Zhuinden** [comment]
> Should i come back every time to mainActivity and add *keys to multistack?

Those are the initialization of the multiple stacks, they're technically just the root keys for each stack. You would only need one of those for each tab you have, not for each key 😛 

------

That said, adding support for multiple Navigator instances would have polluted the API a lot. It would have added following things:

`Navigator.executeDeferredInitialization(String, Context)`
`Navigator.getBackstack(String, Context)`
`Navigator.onBackPressed(String, Context)`
etc.

And I didn't think that's worth the trade-off for the API, so the fragment tag used by Navigator's retained fragment is hard-coded and cannot be configured. :|

https://github.com/Zhuinden/simple-stack/blob/8542759bfd5f82c8998b9b24ded9930c8a156674/simple-stack/src/main/java/com/zhuinden/simplestack/navigator/BackstackHost.java#L76

https://github.com/Zhuinden/simple-stack/blob/8542759bfd5f82c8998b9b24ded9930c8a156674/simple-stack/src/main/java/com/zhuinden/simplestack/navigator/Navigator.java#L222

-------------

That said, it's still possible to flatten the stacks into a single stack, as long as you have a "stack identifier" in the key. The tricky part is that if you need to retain multiple stacks, then you can't use `goTo()` directly when switching between stacks, you'd need to reorder the keys of a given stack identifier to have the new stack at the end of the backstack history.

So it's slightly trickier, but it can be done with one stack. It just needs more punching and some re-ordering using `setHistory` when switching. I don't have a ready-made sample for this atm.

**Comment by Zhuinden** [comment]
I kinda intended to write a sample but I haven't found the free time for it at all yet :(

**Comment by Zhuinden** [comment]
The only way to do it would be to manage one's own BackstackManagers in multiple controllers. This should be reasonably possible with the newly added scoping support.

Navigator multi-stack support is however pretty much out of the question, sorry.

**Comment by Zhuinden** [comment]
With simple-stack 2.0, it was possible to make `Multistack` implementation use multiple backstacks, so theoretically it is possible to wrap the new Multistack implementation in the example (see https://github.com/Zhuinden/simple-stack/blob/f28fcae66287dbb92faefdc905cd2901dd3e7e8d/simple-stack-example-multistack-view/src/main/java/com/zhuinden/simplestackdemomultistack/core/navigation/Multistack.kt ) in a retained headless fragment.

Then it would be the same as Navigator.

The original library however already does Navigator + Backstack, and API-wise it'd be rather awkward to do a `MultistackNavigator` class, so it's best if I still don't add it to the library per say.

It is unfortunate that I waited so many months before making the required changes to make Multistack implementation easier. :disappointed:
