### ISSUE TITLE
Recommended way of clearing backstack when going to a new Screen?

### ISSUE THREAD

**Issue by Saketme** [Zhuinden/simple-stack#80]
Hey Zhuinden, if I want to open screen C from B and also clear the backstack, what's the recommended way of doing this?

`A -> B -> (clear-backstack) -> C`

**Comment by Zhuinden** [comment]
Ah, it's just `backstack.setHistory(HistoryBuilder.single(C.create()), StateChange.FORWARD)`

**Comment by Saketme** [comment]
Got it, thank you!
