### ISSUE TITLE
Is it alright to add a Map<String, View> for sharedElements for Fragment Backstack implementation?

### ISSUE THREAD

**Issue by dev-JE02** [Zhuinden/simple-stack#81]
I would like to implement shared elements and likely add the sharedElements in the key itself. But I am having doubts to pass a Map with View values thinking it would cause OOM errors. Any advice how I can go about implementing it?

**Comment by Zhuinden** [comment]
Keys survive config change, so you should most likely use a `transient Map<String, WeakReference<View>>`. That's how I seem to have used it in the shared element example as well (or at least there it is a Pair of string / weakref)

**Comment by dev-JE02** [comment]
You're right let me try that

**Comment by Zhuinden** [comment]
This is also in [the sample](https://github.com/Zhuinden/simple-stack/blob/e1720066f770bd44e96829bfe269b314fab4f097/simple-stack-example-sharedelement-fragment/src/main/java/com/example/fragmenttransitions/DetailsKey.java#L20) so I'm closing this

Although improvements to that sample are welcome, I'm honestly slightly confused by what transition needs to be set on which fragment. 😓
