### ISSUE TITLE
My layout's fragment was duplicate when the I come back to it

### ISSUE THREAD

**Issue by afermin** [Zhuinden/simple-stack#85]
I implemented your example in kotlin. May you help me? Please.

![image](https://user-images.githubusercontent.com/6080470/37738569-b38e3498-2d57-11e8-91c3-92419c61dffd.png)

**Comment by Zhuinden** [comment]
Duplication can occur if you don't have `equals()` implemented properly. 

However, that cannot happen if you use `Kotlin data class` for key classes (which the `kotlin-example` does, ever since I removed those pesky `object` keys, anyways).

Another option of course is that you are adding the same fragment twice. Even if you add it with the same tag, adding the same fragment in the same transaction will add two instances of the fragment, without warning or anything.

So if you have any fragment transaction outside of the `FragmentStateChanger`, that can cause trouble too.

I don't know your code, so these are just possibilities.

**Comment by afermin** [comment]
I have your same code. When I change attach to replace and detach to remove the fragments working successful .

`class FragmentStateChanger(
    private val fragmentManager: FragmentManager,
    private val containerId: Int
) {
    fun handleStateChange(stateChange: StateChange) {
        val fragmentTransaction = fragmentManager.beginTransaction().apply {
            when (stateChange.direction) {
                StateChange.FORWARD -> {
                    setCustomAnimations(R.anim.slide_in_from_right, R.anim.slide_out_to_left,
                            R.anim.slide_in_from_right, R.anim.slide_out_to_left)
                }
                StateChange.BACKWARD -> {
                    setCustomAnimations(R.anim.slide_in_from_left, R.anim.slide_out_to_right,
                            R.anim.slide_in_from_left, R.anim.slide_out_to_right)
                }
            }
            val previousState = stateChange.getPreviousState<BaseKey>()
            val newState = stateChange.getNewState<BaseKey>()
            for (oldKey in previousState) {
                val fragment = fragmentManager.findFragmentByTag(oldKey.fragmentTag)
                if (fragment != null) {
                    if (!newState.contains(oldKey)) {
                        remove(fragment)
                    } else if (!fragment.isDetached) {
                        detach(fragment)
                    }
                }
            }
            for (newKey in newState) {
                var fragment: Fragment? = fragmentManager.findFragmentByTag(newKey.fragmentTag)
                if (newKey == stateChange.topNewState<Any>()) {
                    if (fragment != null) {
                        if (fragment.isDetached) {
                            attach(fragment)
                            //add(containerId, fragment, newKey.fragmentTag)
                        }
                    } else {
                        fragment = newKey.newFragment()
                        add(containerId, fragment, newKey.fragmentTag)
                    }
                } else {
                    if (fragment != null && !fragment.isDetached) {
                        detach(fragment)
                        //remove(fragment)
                    }
                }
            }
        }

        fragmentTransaction.setReorderingAllowed(true)
        fragmentTransaction.commitAllowingStateLoss()
    }
}`

**Comment by Zhuinden** [comment]
Are you sure it is not `fragmentTransaction.setReorderingAllowed(true)` causing trouble?

**Comment by afermin** [comment]
Yes, I am sure. I am that because I wanted to find a solution but it's the same.

**Comment by Zhuinden** [comment]
Can you show your Activity.onCreate() where the duplication happens?

**Comment by afermin** [comment]
Hi, it is
```
class SearchActivity : NavigationFragmentActivity(){

    @Inject
    lateinit var view: SearchContract.View
    @Inject
    lateinit var presenter: SearchContract.Presenter
    @Inject
    lateinit var model: SearchContract.Model

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initComponent()
        setContentView(view.inflateLayout())
        presenter.onCreate(intent.extras)
        initBackStack(savedInstanceState)
        initFragmentStateChanger()
    }

    override fun onResume() {
        super.onResume()
        presenter.onResume()
    }

    override fun onPause() {
        presenter.onPause()
        super.onPause()
    }

    override fun onDestroy() {
        presenter.onDestroy()
        super.onDestroy()
    }

    private fun initComponent() {
        DaggerSearchComponent.builder()
                .appComponent(MyApplication[this].component())
                .searchModule(SearchModule(this))
                .build()
                .inject(this)
    }


    val observableLocation: Observable<LatLng> by lazy { model.observableLocation }

}

```

**Comment by Zhuinden** [comment]
.... Well most of the logic is inherited so I see nothing from this, how about the `handleStateChange` method in your Activity, if it implements StateChanger in one of its base classes?

---

All of your keys are Data classes, right?

**Comment by afermin** [comment]
Yes, All are like this 
```
@SuppressLint("ParcelCreator")
@Parcelize
data class MapKey(override val tag: String = MAIN) : BaseKey(tag) {

    constructor(list: ArrayList<Establishment>?, tag: String = MAIN) : this(tag) {
        bundleExtra.putParcelableArrayList("object", list)
    }

    override fun createFragment() = MapFragment()

}


class MapKeyTypes {
    companion object {
        const val MAIN = "MapKeyMain"
        const val NORMAL_SEARCH = "MapKeyNormal"
        const val ADAVANCE_SEARCH = "MapKeyAdvance"
    }
}
```

**Comment by afermin** [comment]
Can I add you to my project? I have my project in Bitbucket.

**Comment by Zhuinden** [comment]
@afermin yes, that might simplify things in terms of remote debugging

**Comment by afermin** [comment]
Hi Gabor, I'm sorry for not answering you, I was very busy. I found the solution with this code in the createView:
private var v: View? = null

    ```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initComponent()
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {
        if (v == null) {
            v = view.inflateLayout(container)
        }
        return v
    }
```
I think that the problem is because My fragment inflate the view through FrameLayout layout. I have this in this way because I'm using this structure > [https://github.com/patrick-doyle/android-rxmvp](url)

**Comment by Zhuinden** [comment]
You probably shouldn't cache the view, it is recreated for a reason 😄 

Anyways, I sure wouldn't have figured *that* out without seeing it, glad to hear you found it

**Comment by afermin** [comment]
Yes, you have reason. It isn't the best way to fix my issue.  I share with you my project through the bitbucket. May you check it please? You can find the issue when touch a Specialty and when the app show you the another view you can come back to Specialty and in this moment You will notice de issue.

**Comment by Zhuinden** [comment]
I sincerely hope I answered this one. I don't really remember it. :disappointed:
