### ISSUE TITLE
Add a moveToTop operator

### ISSUE THREAD

**Issue by gonemad** [Zhuinden/simple-stack#86]
It would be cool to add an operator that basically takes an existing key from the history and moves it to the top.  Nothing is replaced.. that key is simply removed from the stack and placed back on top.  If the key is not found in the stack it would add a new one to the top.

Reasoning:

So in my app I have a bunch of fragments that i consider to be "top level".  The user can navigate between them freely using the nav drawer.  Before writing the custom solution to do moveToTop (which i'll paste later), I was just doing a goTo call for each selection in the nav bar.  This works great moving forward, but when pressing the back button it would go through every single key in the exact order they were selected.. even if the same one was selected multiple times.  My desired result would to go back through the previously selected keys without repeating any.

Lets say in a music player app the user goes from the library, to the queue, to the now playing, to the queue, then goes back to the library.  Using goTo, the back button would just go back in that order.  If i tried to check for repeat keys and use something like goUp, it would replace the majority of the history (a goUp to library in the above example would remove the queue and now playing from the stack).  So i ended up writing a kotlin extension to do the job

```
fun Backstack.moveToTop(newKey: Any)
{
    val newHistory = mutableListOf<Any>()
    var isNewKey = true
    for (key in getHistory<Any>())
    {
        if (key == newKey)
            isNewKey = false
        else
            newHistory.add(key)
    }

    newHistory.add(newKey)
    val direction = if (isNewKey)
        StateChange.FORWARD
    else
        StateChange.BACKWARD

    setHistory(newHistory, direction)
}
```

Its no biggie if not added, but i figured others might want a capability like this.

**Comment by Zhuinden** [comment]
Thanks for the request! So I guess on back navigation, you'd still want to go through all the previously selected items, but with the latest having been moved to top over the other previously selected ones, correct? 

One thing that surprises me is the `backward` direction: I would think this operation *always* goes forward.

Note for me: It might also make sense to add a `jumpToRoot` as well.

**Comment by gonemad** [comment]
correct.. so

A -> B -> C -> B -> D -> C      would end up C -> D -> B -> A  when going backwards

I actually have my transitions disabled so i wasnt able to see the diff between forward / backward.. but you are probably right..you would always want to go forward.  Perhaps "bringToFront" is a better name for this operation (i get hung up on naming way to often haha)

I could see jumpToRoot being useful as well

**Comment by Zhuinden** [comment]
I actually kinda prefer `moveToTop` because "front" isn't really a concept in simple-stack :D

if you have transitions disabled for this case, then maybe in reality you'd want to show animation for REPLACE (typically a cross-fade) direction. I guess if I add the method, I'll have to add two overloads: one that is the default (forward), and a second variant that uses replace instead.

**Comment by Zhuinden** [comment]
Will be added by https://github.com/Zhuinden/simple-stack/commit/10e6825facc605e21b3196f11c5e132602144de6 when next version is released

**Comment by Zhuinden** [comment]
1.9.1 is released with `moveToTop` and `jumpToRoot`
