### ISSUE TITLE
fragment -> fragment goback refresh issue.

### ISSUE THREAD

**Issue by leeminsuek** [Zhuinden/simple-stack#89]
My app flow is [A] fragment -> [B] fragment -> back button click(goback() call) -> [A] fragment.

but, [A] fragment refreshed when goBack() method called.
I want not working refresh.

Can you help me?

**Comment by Zhuinden** [comment]
When do you refresh in your code? You can try using hide instead of detach, and show instead of attach in your FragmentStateChanger.

**Comment by leeminsuek** [comment]
Thank you.

I solved the issue.
I changed code for detach to hide and for attach to show.

**Comment by Zhuinden** [comment]
Neat! :)

**Comment by metinvio** [comment]
Hey Gabor (@Zhuinden),
first of all thank you for this amazing library. 

I had the same problem as @leeminsuek so I use show/hide for my BottomNavigation as you suggested, but now it's like there is only one backstack? 

For example:

CASE: Open App -> HomeTab -> open screen home2 ->  switch to ProfileTab -> click back button
Expected behavior: close App because ProfileTab has 0 backstack
Actual behavior: App remains in ProfileTab but removes home2 from HomeTab

What am I doing wrong? Can you please help?

**Comment by Zhuinden** [comment]
Hello! 

For bottom navigation, I typically put the root in the Backstack, and the tabs themselves are managed by the fragment.

Codewise, this is what it looks like: https://github.com/Zhuinden/BottomNavChildFragmentExample/blob/master/app/src/main/java/com/zhuinden/bottomnavfragmentexample/RootFragment.kt

Java version: https://gist.github.com/Zhuinden/4b3d573a3fb538ff4937478e05fc832b

Hopefully that solves the question? Whether you use attach/detach or show/hide shouldn't alter the behavior of what you're experiencing though. Just make sure to also redefine "isNotShowing" too.

**Comment by metinvio** [comment]
Thank you very much for the very quick response. I implemented it like in your tutorial on medium but changed it a bit to fit with BottomNavigationView and also replaced attach/detach with show/hide. Now it behaves like I described before. Is it because of "isNotShowing"? If yes, - stupid question - how do I redefine "isNotShowing"?


`class RootFragment : KeyedFragment(R.layout.root_fragment) {


    private lateinit var stocksFragment: FragmentStackHostFragment
    private lateinit var discoverFragment: FragmentStackHostFragment
    private lateinit var calculatorFragment: FragmentStackHostFragment
    private lateinit var profileFragment: FragmentStackHostFragment

    private lateinit var mNavigation: BottomNavigationView

    private val fragments: Array<Fragment>
        get() = arrayOf(
            stocksFragment,
            discoverFragment,
            calculatorFragment,
            profileFragment
        )
    private var selectedIndex = 0


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        if (savedInstanceState == null) {
            val stocksFragment = FragmentStackHostFragment.newInstance(RootScreen.STOCKS_STACK)
                .also { this.stocksFragment = it }
            val discoverFragment = FragmentStackHostFragment.newInstance(RootScreen.DISCOVER_STACK)
                .also { this.discoverFragment = it }
            val calculatorFragment = FragmentStackHostFragment.newInstance(RootScreen.CALC_STACK)
                .also { this.calculatorFragment = it }
            val profileFragment = FragmentStackHostFragment.newInstance(RootScreen.PROFILE_STACK)
                .also { this.profileFragment = it }


            childFragmentManager.beginTransaction()
                .add(R.id.containerBottomNavContent, stocksFragment, "stocksFragment")
                .add(R.id.containerBottomNavContent, discoverFragment, "discoverFragment")
                .add(R.id.containerBottomNavContent, calculatorFragment, "calculatorFragment")
                .add(R.id.containerBottomNavContent, profileFragment, "profileFragment")
                .selectFragment(selectedIndex)
                .commit()
        } else {
            selectedIndex = savedInstanceState.getInt("selectedIndex", 0)

            stocksFragment =
                childFragmentManager.findFragmentByTag("stocksFragment") as FragmentStackHostFragment
            discoverFragment =
                childFragmentManager.findFragmentByTag("discoverFragment") as FragmentStackHostFragment
            calculatorFragment =
                childFragmentManager.findFragmentByTag("calculatorFragment") as FragmentStackHostFragment
            profileFragment =
                childFragmentManager.findFragmentByTag("profileFragment") as FragmentStackHostFragment
        }
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initView(view)
        mNavigation.selectedItemId = R.id.nav_stocks
    }

    private fun initView(view : View){
        mNavigation = view.findViewById(R.id.bottom_navigation_view)
        mNavigation.setOnItemSelectedListener { item ->
            when (item.itemId) {
                R.id.nav_stocks -> {
                    selectFragment(0)
                }
                R.id.nav_discover -> {
                    selectFragment(1)
                }
                R.id.nav_calculator -> {
                    selectFragment(2)
                }
                R.id.nav_profile -> {
                    selectFragment(3)
                }
            }
            true
        }
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putInt("selectedIndex", selectedIndex)
    }

    private fun FragmentTransaction.selectFragment(selectedIndex: Int): FragmentTransaction {
        fragments.forEachIndexed { index, fragment ->
            if (index == selectedIndex) {
                show(fragment)
            } else {
                hide(fragment)
            }
        }

        setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE)

        return this
    }


    private fun selectFragment(indexToSelect: Int) {
        this.selectedIndex = indexToSelect

        childFragmentManager.beginTransaction()
            .selectFragment(indexToSelect)
            .commit()
    }

}`

**Comment by Zhuinden** [comment]
@metinvio  `isNotShowing` only comes up if you are redefining the `DefaultFragmentStateChanger` behavior to use `show/hide` instead of `attach/detach`, but in this case, the local tab management doesn't have that sort of thing.

The only issue I see in your gist is that you have `mNavigation.selectedItemId = R.id.nav_stocks` but this should be either wrapped in `if(savedInstanceState == null) {`, or should be set when the item is selected in general (inside `selectFragment(int index)` and not in `onViewCreated`.

**Comment by metinvio** [comment]
Ok now I removed `mNavigation.selectedItemId = R.id.nav_stocks` but still back navigation is not working properly.

**Comment by Zhuinden** [comment]
@metinvio now i understand your issue, did you directly take the code from here?

https://github.com/Zhuinden/simple-stack/blob/1f89fb3f55a790ff03846100a444b94a286ec362/samples/multistack-samples/simple-stack-example-multistack-nested-fragment/src/main/java/com/zhuinden/simplestackbottomnavfragmentexample/core/navigation/FragmentStackHostFragment.kt#L37-L51

Theoretically this would work, but in a multi-stack scenario, the back navigation will work correctly only if you use the backstack associated with the given tab, as there is a separate Backstack instance for each tab.

https://github.com/Zhuinden/simple-stack/blob/1f89fb3f55a790ff03846100a444b94a286ec362/samples/multistack-samples/simple-stack-example-multistack-nested-fragment/src/main/java/com/zhuinden/simplestackbottomnavfragmentexample/features/root/first/First1Fragment.kt#L13

**Comment by Zhuinden** [comment]
Actually, it's because `show/hide` only triggers `onHiddenChanged` (not handled in the above code), but not `onPause/onResume`. So using `hide().setMaxLifecycle(STARTED)` and `show().setMaxLifecycle(RESUMED)` would have worked.

**Comment by metinvio** [comment]
Ok that worked. Amazing - thanks again! 😊 Below is the snippet from my RootFragment (for everyone else who got stuck on this):

`private fun FragmentTransaction.selectFragment(selectedIndex: Int): FragmentTransaction {
        fragments.forEachIndexed { index, fragment ->
            if (index == selectedIndex) {
                show(fragment).setMaxLifecycle(fragment,Lifecycle.State.RESUMED)
            } else {
                hide(fragment).setMaxLifecycle(fragment,Lifecycle.State.STARTED)
            }
        }
        setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE)
        return this
    }`
