### ISSUE TITLE
Hi, I want fragment clear.

### ISSUE THREAD

**Issue by leeminsuek** [Zhuinden/simple-stack#92]
but.. I can`t fragment clear;

my code.

` while (fragmentManager.backStackEntryCount > 0) {`
         `   fragmentManager.popBackStackImmediate()`
      `  }`
    `  backstackDelegate.backstack.reset()`
       ` backstackDelegate.backstack.replaceTop(key, StateChange.FORWARD)`

I To be able to clear fragment help me

**Comment by Zhuinden** [comment]
You generally should only use `reset` if you relied on a behavior before 1.6.1 (I think) which makes it so that if you had never executed any state changes.

I think you're probably looking for `backstack.setHistory(History.of(key), StateChange.FORWARD)` instead of reset/replaceTop.

**Comment by Zhuinden** [comment]
I am going to assume that solved your problem, and also I'll make a mental note that I should really deprecate `reset()`. It's just a cause for bugs.

**Comment by Zhuinden** [comment]
``` kotlin
Navigator.getBackstack(requireContext()).setHistory(History.of(SomeScreen()), StateChange.REPLACE)
```

Should do well.
